-- Assign clubs to pyramid based on founding year
-- Oldest clubs in top divisions, newest in bottom divisions

DELETE FROM sheffield_league_clubs;
DELETE FROM sheffield_league_divisions;

-- Create division tables
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-1', 'First Division', 1, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-2', 'Second Division', 2, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-3', 'Third Division', 3, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-4', 'Fourth Division', 4, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-5a', 'Fifth Division A', 5, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-5b', 'Fifth Division B', 5, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-6a', 'Sixth Division West', 6, 'West');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-6b', 'Sixth Division East', 6, 'East');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-6c', 'Sixth Division North', 6, 'North');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-6d', 'Sixth Division South', 6, 'South');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-7a', 'Seventh Division West', 7, 'West');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-7b', 'Seventh Division East', 7, 'East');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-7c', 'Seventh Division North', 7, 'North');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('div-7d', 'Seventh Division South', 7, 'South');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-1', 'Reserve Division 1', 1, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-2', 'Reserve Division 2', 2, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-3', 'Reserve Division 3', 3, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-4', 'Reserve Division 4', 4, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-5a', 'Reserve Division 5A', 5, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-5b', 'Reserve Division 5B', 5, NULL);
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-6a', 'Reserve Division 6A', 6, 'West');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-6b', 'Reserve Division 6B', 6, 'East');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-6c', 'Reserve Division 6C', 6, 'North');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-6d', 'Reserve Division 6D', 6, 'South');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-7a', 'Reserve Division 7A', 7, 'West');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-7b', 'Reserve Division 7B', 7, 'East');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-7c', 'Reserve Division 7C', 7, 'North');
INSERT INTO sheffield_league_divisions (id, name, level, region) VALUES ('res-div-7d', 'Reserve Division 7D', 7, 'South');

-- Assign clubs to divisions

-- div-1
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-fc-div-1', 'div-1', 'sheffield-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-fc-reserves-res-div-1', 'res-div-1', 'sheffield-fc-reserves', 1, 1, 'sheffield-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hallam-fc-div-1', 'div-1', 'hallam-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hallam-fc-reserves-res-div-1', 'res-div-1', 'hallam-fc-reserves', 2, 1, 'hallam-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('cemetery-road-church-fc-div-1', 'div-1', 'cemetery-road-church-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('cemetery-road-church-fc-reserves-res-div-1', 'res-div-1', 'cemetery-road-church-fc-reserves', 3, 1, 'cemetery-road-church-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norfolk-fc-div-1', 'div-1', 'norfolk-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norfolk-fc-reserves-res-div-1', 'res-div-1', 'norfolk-fc-reserves', 4, 1, 'norfolk-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norton-fc-div-1', 'div-1', 'norton-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norton-fc-reserves-res-div-1', 'res-div-1', 'norton-fc-reserves', 5, 1, 'norton-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pitsmoor-fc-div-1', 'div-1', 'pitsmoor-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pitsmoor-fc-reserves-res-div-1', 'res-div-1', 'pitsmoor-fc-reserves', 6, 1, 'pitsmoor-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('york-fc-div-1', 'div-1', 'york-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('york-fc-reserves-res-div-1', 'res-div-1', 'york-fc-reserves', 7, 1, 'york-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('fir-vale-fc-div-1', 'div-1', 'fir-vale-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('fir-vale-fc-reserves-res-div-1', 'res-div-1', 'fir-vale-fc-reserves', 8, 1, 'fir-vale-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('heeley-christ-church-fc-div-1', 'div-1', 'heeley-christ-church-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('heeley-christ-church-fc-reserves-res-div-1', 'res-div-1', 'heeley-christ-church-fc-reserves', 9, 1, 'heeley-christ-church-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('howard-hill-steel-bank-fc-div-1', 'div-1', 'howard-hill-steel-bank-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('howard-hill-steel-bank-fc-reserves-res-div-1', 'res-div-1', 'howard-hill-steel-bank-fc-reserves', 10, 1, 'howard-hill-steel-bank-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('mackenzie-fc-div-1', 'div-1', 'mackenzie-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('mackenzie-fc-reserves-res-div-1', 'res-div-1', 'mackenzie-fc-reserves', 11, 1, 'mackenzie-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('milton-fc-div-1', 'div-1', 'milton-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('milton-fc-reserves-res-div-1', 'res-div-1', 'milton-fc-reserves', 12, 1, 'milton-fc');

-- div-2
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ranmoor-fc-div-2', 'div-2', 'ranmoor-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ranmoor-fc-reserves-res-div-2', 'res-div-2', 'ranmoor-fc-reserves', 1, 1, 'ranmoor-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-george-fc-div-2', 'div-2', 'st-george-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-george-fc-reserves-res-div-2', 'res-div-2', 'st-george-fc-reserves', 2, 1, 'st-george-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-stephen-fc-div-2', 'div-2', 'st-stephen-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-stephen-fc-reserves-res-div-2', 'res-div-2', 'st-stephen-fc-reserves', 3, 1, 'st-stephen-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('united-norfolk-fc-div-2', 'div-2', 'united-norfolk-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('united-norfolk-fc-reserves-res-div-2', 'res-div-2', 'united-norfolk-fc-reserves', 4, 1, 'united-norfolk-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('broomhall-fc-div-2', 'div-2', 'broomhall-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('broomhall-fc-reserves-res-div-2', 'res-div-2', 'broomhall-fc-reserves', 5, 1, 'broomhall-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crabtree-fc-div-2', 'div-2', 'crabtree-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crabtree-fc-reserves-res-div-2', 'res-div-2', 'crabtree-fc-reserves', 6, 1, 'crabtree-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hemsworth-fc-div-2', 'div-2', 'hemsworth-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hemsworth-fc-reserves-res-div-2', 'res-div-2', 'hemsworth-fc-reserves', 7, 1, 'hemsworth-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tudor-fc-div-2', 'div-2', 'tudor-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tudor-fc-reserves-res-div-2', 'res-div-2', 'tudor-fc-reserves', 8, 1, 'tudor-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('united-mechanics-div-2', 'div-2', 'united-mechanics', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('united-mechanics-reserves-res-div-2', 'res-div-2', 'united-mechanics-reserves', 9, 1, 'united-mechanics');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('garrick-fc-div-2', 'div-2', 'garrick-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('garrick-fc-reserves-res-div-2', 'res-div-2', 'garrick-fc-reserves', 10, 1, 'garrick-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('loxley-fc-div-2', 'div-2', 'loxley-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('loxley-fc-reserves-res-div-2', 'res-div-2', 'loxley-fc-reserves', 11, 1, 'loxley-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wellington-fc-div-2', 'div-2', 'wellington-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wellington-fc-reserves-res-div-2', 'res-div-2', 'wellington-fc-reserves', 12, 1, 'wellington-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dore-fc-div-2', 'div-2', 'dore-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dore-fc-reserves-res-div-2', 'res-div-2', 'dore-fc-reserves', 13, 1, 'dore-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('exchange-fc-div-2', 'div-2', 'exchange-fc', 14, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('exchange-fc-reserves-res-div-2', 'res-div-2', 'exchange-fc-reserves', 14, 1, 'exchange-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tapton-fc-div-2', 'div-2', 'tapton-fc', 15, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tapton-fc-reserves-res-div-2', 'res-div-2', 'tapton-fc-reserves', 15, 1, 'tapton-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wednesday-fc-div-2', 'div-2', 'wednesday-fc', 16, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wednesday-fc-reserves-res-div-2', 'res-div-2', 'wednesday-fc-reserves', 16, 1, 'wednesday-fc');

-- div-3
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brincliffe-fc-div-3', 'div-3', 'brincliffe-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brincliffe-fc-reserves-res-div-3', 'res-div-3', 'brincliffe-fc-reserves', 1, 1, 'brincliffe-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-fc-div-3', 'div-3', 'dronfield-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-fc-reserves-res-div-3', 'res-div-3', 'dronfield-fc-reserves', 2, 1, 'dronfield-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hanover-united-fc-div-3', 'div-3', 'hanover-united-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hanover-united-fc-reserves-res-div-3', 'res-div-3', 'hanover-united-fc-reserves', 3, 1, 'hanover-united-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('redhill-fc-div-3', 'div-3', 'redhill-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('redhill-fc-reserves-res-div-3', 'res-div-3', 'redhill-fc-reserves', 4, 1, 'redhill-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('stannington-fc-div-3', 'div-3', 'stannington-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('stannington-fc-reserves-res-div-3', 'res-div-3', 'stannington-fc-reserves', 5, 1, 'stannington-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oxford-fc-div-3', 'div-3', 'oxford-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oxford-fc-reserves-res-div-3', 'res-div-3', 'oxford-fc-reserves', 6, 1, 'oxford-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('parkwood-springs-fc-div-3', 'div-3', 'parkwood-springs-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('parkwood-springs-fc-reserves-res-div-3', 'res-div-3', 'parkwood-springs-fc-reserves', 7, 1, 'parkwood-springs-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-norfolk-fc-div-3', 'div-3', 'sheffield-norfolk-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-norfolk-fc-reserves-res-div-3', 'res-div-3', 'sheffield-norfolk-fc-reserves', 8, 1, 'sheffield-norfolk-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-james-church-fc-div-3', 'div-3', 'st-james-church-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-james-church-fc-reserves-res-div-3', 'res-div-3', 'st-james-church-fc-reserves', 9, 1, 'st-james-church-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('totley-fc-div-3', 'div-3', 'totley-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('totley-fc-reserves-res-div-3', 'res-div-3', 'totley-fc-reserves', 10, 1, 'totley-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('alliance-fc-div-3', 'div-3', 'alliance-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('alliance-fc-reserves-res-div-3', 'res-div-3', 'alliance-fc-reserves', 11, 1, 'alliance-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('attercliffe-christ-church-div-3', 'div-3', 'attercliffe-christ-church', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('attercliffe-christ-church-reserves-res-div-3', 'res-div-3', 'attercliffe-christ-church-reserves', 12, 1, 'attercliffe-christ-church');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('bankers-thursday-div-3', 'div-3', 'bankers-thursday', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('bankers-thursday-reserves-res-div-3', 'res-div-3', 'bankers-thursday-reserves', 13, 1, 'bankers-thursday');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crookes-fc-div-3', 'div-3', 'crookes-fc', 14, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crookes-fc-reserves-res-div-3', 'res-div-3', 'crookes-fc-reserves', 14, 1, 'crookes-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-college-fc-div-3', 'div-3', 'ecclesall-college-fc', 15, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-college-fc-reserves-res-div-3', 'res-div-3', 'ecclesall-college-fc-reserves', 15, 1, 'ecclesall-college-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('engineers-fc-div-3', 'div-3', 'engineers-fc', 16, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('engineers-fc-reserves-res-div-3', 'res-div-3', 'engineers-fc-reserves', 16, 1, 'engineers-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('gleadless-fc-div-3', 'div-3', 'gleadless-fc', 17, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('gleadless-fc-reserves-res-div-3', 'res-div-3', 'gleadless-fc-reserves', 17, 1, 'gleadless-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('lockwood-brothers-fc-div-3', 'div-3', 'lockwood-brothers-fc', 18, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('lockwood-brothers-fc-reserves-res-div-3', 'res-div-3', 'lockwood-brothers-fc-reserves', 18, 1, 'lockwood-brothers-fc');

-- div-4
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('perseverance-fc-div-4', 'div-4', 'perseverance-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('perseverance-fc-reserves-res-div-4', 'res-div-4', 'perseverance-fc-reserves', 1, 1, 'perseverance-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-grammar-school-fc-div-4', 'div-4', 'sheffield-grammar-school-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-grammar-school-fc-reserves-res-div-4', 'res-div-4', 'sheffield-grammar-school-fc-reserves', 2, 1, 'sheffield-grammar-school-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-united-gymnastic-club-div-4', 'div-4', 'sheffield-united-gymnastic-club', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheffield-united-gymnastic-club-reserves-res-div-4', 'res-div-4', 'sheffield-united-gymnastic-club-reserves', 3, 1, 'sheffield-united-gymnastic-club');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('surrey-catholic-club-div-4', 'div-4', 'surrey-catholic-club', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('surrey-catholic-club-reserves-res-div-4', 'res-div-4', 'surrey-catholic-club-reserves', 4, 1, 'surrey-catholic-club');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('talbot-fc-div-4', 'div-4', 'talbot-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('talbot-fc-reserves-res-div-4', 'res-div-4', 'talbot-fc-reserves', 5, 1, 'talbot-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('walkey-new-connexion-fc-div-4', 'div-4', 'walkey-new-connexion-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('walkey-new-connexion-fc-reserves-res-div-4', 'res-div-4', 'walkey-new-connexion-fc-reserves', 6, 1, 'walkey-new-connexion-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('all-saints-night-school-fc-div-4', 'div-4', 'all-saints-night-school-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('all-saints-night-school-fc-reserves-res-div-4', 'res-div-4', 'all-saints-night-school-fc-reserves', 7, 1, 'all-saints-night-school-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('attercliffe-zion-fc-div-4', 'div-4', 'attercliffe-zion-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('attercliffe-zion-fc-reserves-res-div-4', 'res-div-4', 'attercliffe-zion-fc-reserves', 8, 1, 'attercliffe-zion-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('exchange-brewery-fc-div-4', 'div-4', 'exchange-brewery-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('exchange-brewery-fc-reserves-res-div-4', 'res-div-4', 'exchange-brewery-fc-reserves', 9, 1, 'exchange-brewery-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('grimesthorpe-fc-div-4', 'div-4', 'grimesthorpe-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('grimesthorpe-fc-reserves-res-div-4', 'res-div-4', 'grimesthorpe-fc-reserves', 10, 1, 'grimesthorpe-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('millhouses-fc-div-4', 'div-4', 'millhouses-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('millhouses-fc-reserves-res-div-4', 'res-div-4', 'millhouses-fc-reserves', 11, 1, 'millhouses-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('albion-fc-div-4', 'div-4', 'albion-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('albion-fc-reserves-res-div-4', 'res-div-4', 'albion-fc-reserves', 12, 1, 'albion-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brightside-fc-div-4', 'div-4', 'brightside-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brightside-fc-reserves-res-div-4', 'res-div-4', 'brightside-fc-reserves', 13, 1, 'brightside-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('garden-street-fc-div-4', 'div-4', 'garden-street-fc', 14, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('garden-street-fc-reserves-res-div-4', 'res-div-4', 'garden-street-fc-reserves', 14, 1, 'garden-street-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norfolk-works-fc-div-4', 'div-4', 'norfolk-works-fc', 15, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norfolk-works-fc-reserves-res-div-4', 'res-div-4', 'norfolk-works-fc-reserves', 15, 1, 'norfolk-works-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pye-bank-fc-div-4', 'div-4', 'pye-bank-fc', 16, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pye-bank-fc-reserves-res-div-4', 'res-div-4', 'pye-bank-fc-reserves', 16, 1, 'pye-bank-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('birley-fc-div-4', 'div-4', 'birley-fc', 17, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('birley-fc-reserves-res-div-4', 'res-div-4', 'birley-fc-reserves', 17, 1, 'birley-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('boston-street-fc-div-4', 'div-4', 'boston-street-fc', 18, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('boston-street-fc-reserves-res-div-4', 'res-div-4', 'boston-street-fc-reserves', 18, 1, 'boston-street-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('cherrytree-fc-div-4', 'div-4', 'cherrytree-fc', 19, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('cherrytree-fc-reserves-res-div-4', 'res-div-4', 'cherrytree-fc-reserves', 19, 1, 'cherrytree-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('clifford-fc-div-4', 'div-4', 'clifford-fc', 20, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('clifford-fc-reserves-res-div-4', 'res-div-4', 'clifford-fc-reserves', 20, 1, 'clifford-fc');

-- div-5a
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crosspool-rangers-fc-div-5a', 'div-5a', 'crosspool-rangers-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crosspool-rangers-fc-reserves-res-div-5a', 'res-div-5a', 'crosspool-rangers-fc-reserves', 1, 1, 'crosspool-rangers-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesfield-fc-div-5a', 'div-5a', 'ecclesfield-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesfield-fc-reserves-res-div-5a', 'res-div-5a', 'ecclesfield-fc-reserves', 2, 1, 'ecclesfield-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('endcliffe-fc-div-5a', 'div-5a', 'endcliffe-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('endcliffe-fc-reserves-res-div-5a', 'res-div-5a', 'endcliffe-fc-reserves', 3, 1, 'endcliffe-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('grange-fc-div-5a', 'div-5a', 'grange-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('grange-fc-reserves-res-div-5a', 'res-div-5a', 'grange-fc-reserves', 4, 1, 'grange-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('intake-fc-div-5a', 'div-5a', 'intake-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('intake-fc-reserves-res-div-5a', 'res-div-5a', 'intake-fc-reserves', 5, 1, 'intake-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oughtibridge-fc-div-5a', 'div-5a', 'oughtibridge-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oughtibridge-fc-reserves-res-div-5a', 'res-div-5a', 'oughtibridge-fc-reserves', 6, 1, 'oughtibridge-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('owlerton-fc-div-5a', 'div-5a', 'owlerton-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('owlerton-fc-reserves-res-div-5a', 'res-div-5a', 'owlerton-fc-reserves', 7, 1, 'owlerton-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('owlerton-reform-fc-div-5a', 'div-5a', 'owlerton-reform-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('owlerton-reform-fc-reserves-res-div-5a', 'res-div-5a', 'owlerton-reform-fc-reserves', 8, 1, 'owlerton-reform-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('philadelphia-fc-div-5a', 'div-5a', 'philadelphia-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('philadelphia-fc-reserves-res-div-5a', 'res-div-5a', 'philadelphia-fc-reserves', 9, 1, 'philadelphia-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pitsmoor-coal-company-fc-div-5a', 'div-5a', 'pitsmoor-coal-company-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pitsmoor-coal-company-fc-reserves-res-div-5a', 'res-div-5a', 'pitsmoor-coal-company-fc-reserves', 10, 1, 'pitsmoor-coal-company-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('roebuck-fc-div-5a', 'div-5a', 'roebuck-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('roebuck-fc-reserves-res-div-5a', 'res-div-5a', 'roebuck-fc-reserves', 11, 1, 'roebuck-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sharrow-rangers-fc-div-5a', 'div-5a', 'sharrow-rangers-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sharrow-rangers-fc-reserves-res-div-5a', 'res-div-5a', 'sharrow-rangers-fc-reserves', 12, 1, 'sharrow-rangers-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sherrington-fc-div-5a', 'div-5a', 'sherrington-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sherrington-fc-reserves-res-div-5a', 'res-div-5a', 'sherrington-fc-reserves', 13, 1, 'sherrington-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tennant-brothers-co-fc-div-5a', 'div-5a', 'tennant-brothers-co-fc', 14, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tennant-brothers-co-fc-reserves-res-div-5a', 'res-div-5a', 'tennant-brothers-co-fc-reserves', 14, 1, 'tennant-brothers-co-fc');

-- div-5b
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('victoria-burngreave-fc-div-5b', 'div-5b', 'victoria-burngreave-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('victoria-burngreave-fc-reserves-res-div-5b', 'res-div-5b', 'victoria-burngreave-fc-reserves', 1, 1, 'victoria-burngreave-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wardsend-steel-works-fc-div-5b', 'div-5b', 'wardsend-steel-works-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wardsend-steel-works-fc-reserves-res-div-5b', 'res-div-5b', 'wardsend-steel-works-fc-reserves', 2, 1, 'wardsend-steel-works-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('west-end-fc-div-5b', 'div-5b', 'west-end-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('west-end-fc-reserves-res-div-5b', 'res-div-5b', 'west-end-fc-reserves', 3, 1, 'west-end-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('weston-fc-div-5b', 'div-5b', 'weston-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('weston-fc-reserves-res-div-5b', 'res-div-5b', 'weston-fc-reserves', 4, 1, 'weston-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('105th-regiment-div-5b', 'div-5b', '105th-regiment', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('105th-regiment-reserves-res-div-5b', 'res-div-5b', '105th-regiment-reserves', 5, 1, '105th-regiment');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('atkin-brothers-fc-div-5b', 'div-5b', 'atkin-brothers-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('atkin-brothers-fc-reserves-res-div-5b', 'res-div-5b', 'atkin-brothers-fc-reserves', 6, 1, 'atkin-brothers-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('atlas-fc-div-5b', 'div-5b', 'atlas-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('atlas-fc-reserves-res-div-5b', 'res-div-5b', 'atlas-fc-reserves', 7, 1, 'atlas-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brookes-crookes-fc-div-5b', 'div-5b', 'brookes-crookes-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brookes-crookes-fc-reserves-res-div-5b', 'res-div-5b', 'brookes-crookes-fc-reserves', 8, 1, 'brookes-crookes-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('broomfield-fc-div-5b', 'div-5b', 'broomfield-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('broomfield-fc-reserves-res-div-5b', 'res-div-5b', 'broomfield-fc-reserves', 9, 1, 'broomfield-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('carnforth-fc-div-5b', 'div-5b', 'carnforth-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('carnforth-fc-reserves-res-div-5b', 'res-div-5b', 'carnforth-fc-reserves', 10, 1, 'carnforth-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('deep-pits-fc-div-5b', 'div-5b', 'deep-pits-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('deep-pits-fc-reserves-res-div-5b', 'res-div-5b', 'deep-pits-fc-reserves', 11, 1, 'deep-pits-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-church-fc-div-5b', 'div-5b', 'ecclesall-church-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-church-fc-reserves-res-div-5b', 'res-div-5b', 'ecclesall-church-fc-reserves', 12, 1, 'ecclesall-church-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-fc-div-5b', 'div-5b', 'ecclesall-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-fc-reserves-res-div-5b', 'res-div-5b', 'ecclesall-fc-reserves', 13, 1, 'ecclesall-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('fenton-brothers-fc-div-5b', 'div-5b', 'fenton-brothers-fc', 14, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('fenton-brothers-fc-reserves-res-div-5b', 'res-div-5b', 'fenton-brothers-fc-reserves', 14, 1, 'fenton-brothers-fc');

-- div-6a
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('good-intent-fc-div-6a', 'div-6a', 'good-intent-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('good-intent-fc-reserves-res-div-6a', 'res-div-6a', 'good-intent-fc-reserves', 1, 1, 'good-intent-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('handsworth-fc-div-6a', 'div-6a', 'handsworth-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('handsworth-fc-reserves-res-div-6a', 'res-div-6a', 'handsworth-fc-reserves', 2, 1, 'handsworth-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('heeley-victoria-fc-div-6a', 'div-6a', 'heeley-victoria-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('heeley-victoria-fc-reserves-res-div-6a', 'res-div-6a', 'heeley-victoria-fc-reserves', 3, 1, 'heeley-victoria-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hollinsend-fc-div-6a', 'div-6a', 'hollinsend-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hollinsend-fc-reserves-res-div-6a', 'res-div-6a', 'hollinsend-fc-reserves', 4, 1, 'hollinsend-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('kenwood-fc-div-6a', 'div-6a', 'kenwood-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('kenwood-fc-reserves-res-div-6a', 'res-div-6a', 'kenwood-fc-reserves', 5, 1, 'kenwood-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('lo-good-templars-fc-div-6a', 'div-6a', 'lo-good-templars-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('lo-good-templars-fc-reserves-res-div-6a', 'res-div-6a', 'lo-good-templars-fc-reserves', 6, 1, 'lo-good-templars-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('mill-sands-fc-div-6a', 'div-6a', 'mill-sands-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('mill-sands-fc-reserves-res-div-6a', 'res-div-6a', 'mill-sands-fc-reserves', 7, 1, 'mill-sands-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('montague-fc-div-6a', 'div-6a', 'montague-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('montague-fc-reserves-res-div-6a', 'res-div-6a', 'montague-fc-reserves', 8, 1, 'montague-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('mount-tabor-fc-div-6a', 'div-6a', 'mount-tabor-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('mount-tabor-fc-reserves-res-div-6a', 'res-div-6a', 'mount-tabor-fc-reserves', 9, 1, 'mount-tabor-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('nether-fc-div-6a', 'div-6a', 'nether-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('nether-fc-reserves-res-div-6a', 'res-div-6a', 'nether-fc-reserves', 10, 1, 'nether-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norton-mount-view-fc-div-6a', 'div-6a', 'norton-mount-view-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('norton-mount-view-fc-reserves-res-div-6a', 'res-div-6a', 'norton-mount-view-fc-reserves', 11, 1, 'norton-mount-view-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oak-street-fc-div-6a', 'div-6a', 'oak-street-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oak-street-fc-reserves-res-div-6a', 'res-div-6a', 'oak-street-fc-reserves', 12, 1, 'oak-street-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('owlerton-united-fc-div-6a', 'div-6a', 'owlerton-united-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('owlerton-united-fc-reserves-res-div-6a', 'res-div-6a', 'owlerton-united-fc-reserves', 13, 1, 'owlerton-united-fc');

-- div-6b
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('park-united-fc-div-6b', 'div-6b', 'park-united-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('park-united-fc-reserves-res-div-6b', 'res-div-6b', 'park-united-fc-reserves', 1, 1, 'park-united-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('polar-star-fc-div-6b', 'div-6b', 'polar-star-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('polar-star-fc-reserves-res-div-6b', 'res-div-6b', 'polar-star-fc-reserves', 2, 1, 'polar-star-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('port-mahon-fc-div-6b', 'div-6b', 'port-mahon-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('port-mahon-fc-reserves-res-div-6b', 'res-div-6b', 'port-mahon-fc-reserves', 3, 1, 'port-mahon-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('providence-fc-div-6b', 'div-6b', 'providence-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('providence-fc-reserves-res-div-6b', 'res-div-6b', 'providence-fc-reserves', 4, 1, 'providence-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('regents-works-fc-div-6b', 'div-6b', 'regents-works-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('regents-works-fc-reserves-res-div-6b', 'res-div-6b', 'regents-works-fc-reserves', 5, 1, 'regents-works-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheaf-fc-div-6b', 'div-6b', 'sheaf-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('sheaf-fc-reserves-res-div-6b', 'res-div-6b', 'sheaf-fc-reserves', 6, 1, 'sheaf-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('shrewsbury-road-fc-div-6b', 'div-6b', 'shrewsbury-road-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('shrewsbury-road-fc-reserves-res-div-6b', 'res-div-6b', 'shrewsbury-road-fc-reserves', 7, 1, 'shrewsbury-road-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-michaels-angels-fc-div-6b', 'div-6b', 'st-michaels-angels-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-michaels-angels-fc-reserves-res-div-6b', 'res-div-6b', 'st-michaels-angels-fc-reserves', 8, 1, 'st-michaels-angels-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-silas-fc-div-6b', 'div-6b', 'st-silas-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('st-silas-fc-reserves-res-div-6b', 'res-div-6b', 'st-silas-fc-reserves', 9, 1, 'st-silas-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tabernacle-fc-div-6b', 'div-6b', 'tabernacle-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('tabernacle-fc-reserves-res-div-6b', 'res-div-6b', 'tabernacle-fc-reserves', 10, 1, 'tabernacle-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('unitarian-fc-div-6b', 'div-6b', 'unitarian-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('unitarian-fc-reserves-res-div-6b', 'res-div-6b', 'unitarian-fc-reserves', 11, 1, 'unitarian-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('white-star-fc-div-6b', 'div-6b', 'white-star-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('white-star-fc-reserves-res-div-6b', 'res-div-6b', 'white-star-fc-reserves', 12, 1, 'white-star-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wingfield-rowbotham-fc-div-6b', 'div-6b', 'wingfield-rowbotham-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wingfield-rowbotham-fc-reserves-res-div-6b', 'res-div-6b', 'wingfield-rowbotham-fc-reserves', 13, 1, 'wingfield-rowbotham-fc');

-- div-6c
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('woodseats-fc-div-6c', 'div-6c', 'woodseats-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('woodseats-fc-reserves-res-div-6c', 'res-div-6c', 'woodseats-fc-reserves', 1, 1, 'woodseats-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('young-broomhall-fc-div-6c', 'div-6c', 'young-broomhall-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('young-broomhall-fc-reserves-res-div-6c', 'res-div-6c', 'young-broomhall-fc-reserves', 2, 1, 'young-broomhall-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('alexandra-fc-div-6c', 'div-6c', 'alexandra-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('alexandra-fc-reserves-res-div-6c', 'res-div-6c', 'alexandra-fc-reserves', 3, 1, 'alexandra-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('aston-fc-div-6c', 'div-6c', 'aston-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('aston-fc-reserves-res-div-6c', 'res-div-6c', 'aston-fc-reserves', 4, 1, 'aston-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('atlantic-juniors-fc-div-6c', 'div-6c', 'atlantic-juniors-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('atlantic-juniors-fc-reserves-res-div-6c', 'res-div-6c', 'atlantic-juniors-fc-reserves', 5, 1, 'atlantic-juniors-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('bellefield-fc-div-6c', 'div-6c', 'bellefield-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('bellefield-fc-reserves-res-div-6c', 'res-div-6c', 'bellefield-fc-reserves', 6, 1, 'bellefield-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brown-bailey-dixon-fc-div-6c', 'div-6c', 'brown-bailey-dixon-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('brown-bailey-dixon-fc-reserves-res-div-6c', 'res-div-6c', 'brown-bailey-dixon-fc-reserves', 7, 1, 'brown-bailey-dixon-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('carbrook-united-fc-div-6c', 'div-6c', 'carbrook-united-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('carbrook-united-fc-reserves-res-div-6c', 'res-div-6c', 'carbrook-united-fc-reserves', 8, 1, 'carbrook-united-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('chester-brothers-fc-div-6c', 'div-6c', 'chester-brothers-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('chester-brothers-fc-reserves-res-div-6c', 'res-div-6c', 'chester-brothers-fc-reserves', 9, 1, 'chester-brothers-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('clough-house-fc-div-6c', 'div-6c', 'clough-house-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('clough-house-fc-reserves-res-div-6c', 'res-div-6c', 'clough-house-fc-reserves', 10, 1, 'clough-house-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('cornish-place-fc-div-6c', 'div-6c', 'cornish-place-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('cornish-place-fc-reserves-res-div-6c', 'res-div-6c', 'cornish-place-fc-reserves', 11, 1, 'cornish-place-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crookes-united-fc-div-6c', 'div-6c', 'crookes-united-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('crookes-united-fc-reserves-res-div-6c', 'res-div-6c', 'crookes-united-fc-reserves', 12, 1, 'crookes-united-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-baptists-fc-div-6c', 'div-6c', 'dronfield-baptists-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-baptists-fc-reserves-res-div-6c', 'res-div-6c', 'dronfield-baptists-fc-reserves', 13, 1, 'dronfield-baptists-fc');

-- div-6d
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-free-church-fc-div-6d', 'div-6d', 'dronfield-free-church-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-free-church-fc-reserves-res-div-6d', 'res-div-6d', 'dronfield-free-church-fc-reserves', 1, 1, 'dronfield-free-church-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-independent-fc-div-6d', 'div-6d', 'dronfield-independent-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-independent-fc-reserves-res-div-6d', 'res-div-6d', 'dronfield-independent-fc-reserves', 2, 1, 'dronfield-independent-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-united-fc-div-6d', 'div-6d', 'dronfield-united-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('dronfield-united-fc-reserves-res-div-6d', 'res-div-6d', 'dronfield-united-fc-reserves', 3, 1, 'dronfield-united-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ebernezer-reform-fc-div-6d', 'div-6d', 'ebernezer-reform-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ebernezer-reform-fc-reserves-res-div-6d', 'res-div-6d', 'ebernezer-reform-fc-reserves', 4, 1, 'ebernezer-reform-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-united-fc-div-6d', 'div-6d', 'ecclesall-united-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('ecclesall-united-fc-reserves-res-div-6d', 'res-div-6d', 'ecclesall-united-fc-reserves', 5, 1, 'ecclesall-united-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('harold-fc-div-6d', 'div-6d', 'harold-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('harold-fc-reserves-res-div-6d', 'res-div-6d', 'harold-fc-reserves', 6, 1, 'harold-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('heeley-united-fc-div-6d', 'div-6d', 'heeley-united-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('heeley-united-fc-reserves-res-div-6d', 'res-div-6d', 'heeley-united-fc-reserves', 7, 1, 'heeley-united-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hillsborough-fc-div-6d', 'div-6d', 'hillsborough-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hillsborough-fc-reserves-res-div-6d', 'res-div-6d', 'hillsborough-fc-reserves', 8, 1, 'hillsborough-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hope-club-div-6d', 'div-6d', 'hope-club', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hope-club-reserves-res-div-6d', 'res-div-6d', 'hope-club-reserves', 9, 1, 'hope-club');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('howard-street-fc-div-6d', 'div-6d', 'howard-street-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('howard-street-fc-reserves-res-div-6d', 'res-div-6d', 'howard-street-fc-reserves', 10, 1, 'howard-street-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hutton-son-fc-div-6d', 'div-6d', 'hutton-son-fc', 11, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('hutton-son-fc-reserves-res-div-6d', 'res-div-6d', 'hutton-son-fc-reserves', 11, 1, 'hutton-son-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('j-round-son-fc-div-6d', 'div-6d', 'j-round-son-fc', 12, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('j-round-son-fc-reserves-res-div-6d', 'res-div-6d', 'j-round-son-fc-reserves', 12, 1, 'j-round-son-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('langsett-road-fc-div-6d', 'div-6d', 'langsett-road-fc', 13, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('langsett-road-fc-reserves-res-div-6d', 'res-div-6d', 'langsett-road-fc-reserves', 13, 1, 'langsett-road-fc');

-- div-7a
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('malinda-works-fc-div-7a', 'div-7a', 'malinda-works-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('malinda-works-fc-reserves-res-div-7a', 'res-div-7a', 'malinda-works-fc-reserves', 1, 1, 'malinda-works-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('manor-fc-div-7a', 'div-7a', 'manor-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('manor-fc-reserves-res-div-7a', 'res-div-7a', 'manor-fc-reserves', 2, 1, 'manor-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('minerva-fc-div-7a', 'div-7a', 'minerva-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('minerva-fc-reserves-res-div-7a', 'res-div-7a', 'minerva-fc-reserves', 3, 1, 'minerva-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('msl-loco-fc-div-7a', 'div-7a', 'msl-loco-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('msl-loco-fc-reserves-res-div-7a', 'res-div-7a', 'msl-loco-fc-reserves', 4, 1, 'msl-loco-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('netherthorpe-fc-div-7a', 'div-7a', 'netherthorpe-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('netherthorpe-fc-reserves-res-div-7a', 'res-div-7a', 'netherthorpe-fc-reserves', 5, 1, 'netherthorpe-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oxford-wanderers-fc-div-7a', 'div-7a', 'oxford-wanderers-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('oxford-wanderers-fc-reserves-res-div-7a', 'res-div-7a', 'oxford-wanderers-fc-reserves', 6, 1, 'oxford-wanderers-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('parkwood-juniors-fc-div-7a', 'div-7a', 'parkwood-juniors-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('parkwood-juniors-fc-reserves-res-div-7a', 'res-div-7a', 'parkwood-juniors-fc-reserves', 7, 1, 'parkwood-juniors-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pye-bank-free-church-fc-div-7a', 'div-7a', 'pye-bank-free-church-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('pye-bank-free-church-fc-reserves-res-div-7a', 'res-div-7a', 'pye-bank-free-church-fc-reserves', 8, 1, 'pye-bank-free-church-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('r-sorby-son-fc-div-7a', 'div-7a', 'r-sorby-son-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('r-sorby-son-fc-reserves-res-div-7a', 'res-div-7a', 'r-sorby-son-fc-reserves', 9, 1, 'r-sorby-son-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('red-rose-fc-div-7a', 'div-7a', 'red-rose-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('red-rose-fc-reserves-res-div-7a', 'res-div-7a', 'red-rose-fc-reserves', 10, 1, 'red-rose-fc');

-- div-7b
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('south-view-fc-div-7b', 'div-7b', 'south-view-fc', 1, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('south-view-fc-reserves-res-div-7b', 'res-div-7b', 'south-view-fc-reserves', 1, 1, 'south-view-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('stag-home-fc-div-7b', 'div-7b', 'stag-home-fc', 2, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('stag-home-fc-reserves-res-div-7b', 'res-div-7b', 'stag-home-fc-reserves', 2, 1, 'stag-home-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('stanley-street-fc-div-7b', 'div-7b', 'stanley-street-fc', 3, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('stanley-street-fc-reserves-res-div-7b', 'res-div-7b', 'stanley-street-fc-reserves', 3, 1, 'stanley-street-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('trinity-fc-div-7b', 'div-7b', 'trinity-fc', 4, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('trinity-fc-reserves-res-div-7b', 'res-div-7b', 'trinity-fc-reserves', 4, 1, 'trinity-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('upperthorpe-fc-div-7b', 'div-7b', 'upperthorpe-fc', 5, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('upperthorpe-fc-reserves-res-div-7b', 'res-div-7b', 'upperthorpe-fc-reserves', 5, 1, 'upperthorpe-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('washington-fc-div-7b', 'div-7b', 'washington-fc', 6, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('washington-fc-reserves-res-div-7b', 'res-div-7b', 'washington-fc-reserves', 6, 1, 'washington-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('weston-rovers-fc-div-7b', 'div-7b', 'weston-rovers-fc', 7, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('weston-rovers-fc-reserves-res-div-7b', 'res-div-7b', 'weston-rovers-fc-reserves', 7, 1, 'weston-rovers-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wincobank-fc-div-7b', 'div-7b', 'wincobank-fc', 8, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wincobank-fc-reserves-res-div-7b', 'res-div-7b', 'wincobank-fc-reserves', 8, 1, 'wincobank-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('woodhouse-fc-div-7b', 'div-7b', 'woodhouse-fc', 9, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('woodhouse-fc-reserves-res-div-7b', 'res-div-7b', 'woodhouse-fc-reserves', 9, 1, 'woodhouse-fc');
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wostenholm-fc-div-7b', 'div-7b', 'wostenholm-fc', 10, 0, NULL);
INSERT INTO sheffield_league_clubs (id, division_id, club_id, position_in_division, is_reserve_team, reserve_of_club_id) VALUES ('wostenholm-fc-reserves-res-div-7b', 'res-div-7b', 'wostenholm-fc-reserves', 10, 1, 'wostenholm-fc');

-- div-7c

-- div-7d

SELECT COUNT(*) as assigned_clubs FROM sheffield_league_clubs;
SELECT division_id, COUNT(*) as clubs FROM sheffield_league_clubs WHERE is_reserve_team = 0 GROUP BY division_id ORDER BY division_id;
