-- Drop and recreate sheffield_clubs table with correct schema
DROP TABLE IF EXISTS sheffield_clubs;

CREATE TABLE sheffield_clubs (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT,
    founded_year INTEGER,
    ground_name TEXT,
    ground_capacity INTEGER,
    city TEXT,
    region TEXT,
    primary_color TEXT,
    secondary_color TEXT,
    origin TEXT
);

-- Insert all 187 Sheffield clubs
INSERT INTO sheffield_clubs (id, name, short_name, founded_year, ground_name, city, region, primary_color, secondary_color, origin) VALUES
('sheffield-fc', 'Sheffield FC', 'SHF', 1857, 'East Bank', 'Sheffield', 'Yorkshire', '#FF0000', '#FFFFFF', 'played at East Bank'),
('hallam-fc', 'Hallam FC', 'HAL', 1860, 'Sandygate', 'Sheffield', 'Yorkshire', '#0000FF', '#FFFFFF', 'play at Sandygate'),
('norfolk-fc', 'Norfolk FC', 'NOR', 1861, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#008000', '#FFFFFF', 'played at Norfolk Park'),
('cemetery-road-church-fc', 'Cemetery Road Church FC', 'CRC', 1861, 'Hunters Bar', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'Oldest church club, played at Hunters Bar'),
('york-fc', 'York FC', 'YRK', 1861, 'Endcliffe Cricket Ground', 'Sheffield', 'Yorkshire', '#FFA500', '#000000', 'From York Hotel, Broomhill, played at Endcliffe Cricket Ground, N Creswick was President'),
('norton-fc', 'Norton FC', 'NTN', 1861, 'Oaks Park', 'Norton', 'Yorkshire', '#8B4513', '#FFFFFF', 'played at Oaks Park, Norton'),
('pitsmoor-fc', 'Pitsmoor FC', 'PIT', 1861, 'Pitsmoor CC', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'played at Pitsmoor CC, now SUFC Academy'),
('fir-vale-fc', 'Fir Vale FC', 'FIR', 1862, 'Pitsmoor CC', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'played at Pitsmoor CC, now SUFC Academy'),
('heeley-christ-church-fc', 'Heeley Christ Church FC', 'HCC', 1862, 'Meersbrook Park', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'played at Meersbrook Park'),
('mackenzie-fc', 'Mackenzie FC', 'MAC', 1862, 'Myrtle Road', 'Heeley', 'Yorkshire', '#2F4F4F', '#FFFFFF', 'played at Myrtle Road, Heeley'),
('milton-fc', 'Milton FC', 'MIL', 1862, 'Cremorne Gardens', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'played at Cremorne Gardens, London Road'),
('howard-hill-steel-bank-fc', 'Howard Hill Steel Bank FC', 'HHS', 1862, 'Howard Hotel', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'Met in Howard Hotel, Howard Road'),
('ranmoor-fc', 'Ranmoor FC', 'RAN', 1862, 'Ranmoor', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'played in Ranmoor'),
('st-george-fc', 'St George FC', 'STG', 1862, 'Broad Lane', 'Sheffield', 'Yorkshire', '#FF0000', '#FFFFFF', 'From St George''s Church, Broad Lane'),
('st-stephen-fc', 'St Stephen FC', 'STS', 1862, 'Crookes', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'From St Stephen''s Church Fawcett Road Netherthorpe. Played at Crookes'),
('united-norfolk-fc', 'United Norfolk FC', 'UNF', 1862, 'Unknown', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'Origins uncertain'),
('crabtree-fc', 'Crabtree FC', 'CRB', 1863, 'Fir Vale', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'Likely from Fir Vale area'),
('broomhall-fc', 'Broomhall FC', 'BRH', 1863, 'Ecclesall Road', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'played at Ecclesall Road'),
('tudor-fc', 'Tudor FC', 'TUD', 1863, 'Unknown', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', ''),
('wh-hutchinson-fc', 'W & H Hutchinson''s FC', 'WHH', 1863, 'Unknown', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', ''),
('hemsworth-fc', 'Hemsworth FC', 'HEM', 1863, 'Unknown', 'Sheffield', 'Yorkshire', '#2F4F4F', '#FFFFFF', ''),
('united-mechanics', 'United Mechanics', 'UNM', 1865, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'played at Norfolk Park'),
('garrick-fc', 'Garrick FC', 'GAR', 1866, 'East Bank', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'played at East Bank'),
('wellington-fc', 'Wellington FC', 'WEL', 1866, 'Hounsfield Park', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'played at Hounsfield Park near Bramall Lane'),
('loxley-fc', 'Loxley FC', 'LOX', 1866, 'The Rodney Inn', 'Loxley', 'Yorkshire', '#228B22', '#FFFFFF', 'Met at The Rodney Inn, Loxley'),
('wednesday-fc', 'Wednesday FC', 'WED', 1867, 'Highfields', 'Sheffield', 'Yorkshire', '#0000FF', '#FFFFFF', 'played at Highfields, now Hillsborough'),
('exchange-fc', 'Exchange FC', 'EXC', 1867, 'Hallam''s Farm', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'played at Hallam''s Farm, now Hyde Park Flats'),
('dore-fc', 'Dore FC', 'DOR', 1867, 'The Devonshire Arms', 'Dore', 'Yorkshire', '#8B0000', '#FFFFFF', 'Met at The Devonshire Arms, Dore'),
('tapton-fc', 'Tapton FC', 'TAP', 1867, 'Tapton Hall', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'Based at Tapton Hall'),
('dronfield-fc', 'Dronfield FC', 'DRN', 1868, 'Bagley''s Field', 'Dronfield', 'Yorkshire', '#006400', '#FFFFFF', 'played at Bagley''s Field, Dronfield'),
('parkwood-springs-fc', 'Parkwood Springs FC', 'PKS', 1869, 'Parkwood Springs Recreation Ground', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'played at Parkwood Springs Recreation Ground'),
('brincliffe-fc', 'Brincliffe FC', 'BRN', 1868, 'Cherry Tree Farm', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'played at Cherry Tree Farm, near Union pub'),
('hanover-united-fc', 'Hanover United FC', 'HAN', 1868, 'Crookes', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'played at Crookes'),
('stannington-fc', 'Stannington FC', 'STN', 1868, 'Unknown', 'Stannington', 'Yorkshire', '#696969', '#FFFFFF', 'unknown ground location'),
('redhill-fc', 'Redhill FC', 'RED', 1868, 'Winter Street', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'played at Winter Street, near Weston Park'),
('oxford-fc', 'Oxford FC', 'OXF', 1869, 'Ecclesall Road', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'played at Ecclesall Road'),
('totley-fc', 'Totley FC', 'TOT', 1869, 'Cross Scythes Inn', 'Totley', 'Yorkshire', '#8B0000', '#FFFFFF', 'played at field next to Cross Scythes Inn, Totley'),
('sheffield-norfolk-fc', 'Sheffield Norfolk FC', 'SNF', 1869, 'Unknown', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', ''),
('st-vincents', 'St Vincent''s', 'STV', 1869, 'Queens Ground', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'from Solly Street – played at Queens Ground'),
('st-james-church-fc', 'St James Church FC', 'SJC', 1869, 'Norton Lees Lane', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'played at Norton Lees Lane'),
('lockwood-brothers-fc', 'Lockwood Brothers FC', 'LKB', 1870, 'Hunters Bar', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'played at Hunters Bar, oldest works club'),
('talbot-fc', 'Talbot FC', 'TAL', 1870, 'Norfolk Road', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'played at Norfolk Road'),
('sheffield-united-gymnastic-club', 'Sheffield United Gymnastic Club', 'SUG', 1870, 'Unknown', 'Sheffield', 'Yorkshire', '#FF0000', '#000000', ''),
('ecclesall-college-fc', 'Ecclesall College FC', 'ECL', 1870, 'Unknown', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', ''),
('sheffield-grammar-school-fc', 'Sheffield Grammar School FC', 'SGS', 1870, 'Unknown', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', ''),
('surrey-catholic-club', 'Surrey Catholic Club', 'SCC', 1870, 'The Farm', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'played at The Farm, now Sheffield College'),
('attercliffe-christ-church', 'Attercliffe (Christ Church)', 'ACC', 1870, 'The Old Forge Ground', 'Attercliffe', 'Yorkshire', '#DC143C', '#FFFFFF', 'played at The Old Forge Ground, Shirland Lane'),
('walkey-new-connexion-fc', 'Walkey New Connexion FC', 'WNC', 1870, 'Queens Ground', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'played at Queens Ground, Hillsborough'),
('crookes-fc', 'Crookes FC', 'CRK', 1870, 'Lydgate Lane', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'played at Lydgate Lane'),
('bankers-thursday', 'Bankers / Thursday', 'BNK', 1870, 'Hunters Bar', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'played at Hunters Bar'),
('alliance-fc', 'Alliance FC', 'ALN', 1870, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'played at Norfolk Park'),
('perseverance-fc', 'Perseverance FC', 'PER', 1870, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'played at Norfolk Park'),
('gleadless-fc', 'Gleadless FC', 'GLD', 1870, 'Charnock Hall', 'Gleadless', 'Yorkshire', '#8B4513', '#FFFFFF', 'played at Charnock Hall, Gleadless'),
('engineers-fc', 'Engineers FC', 'ENG', 1870, 'Endcliffe Crescent', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'Played at Endcliffe Crescent'),
('attercliffe-zion-fc', 'Attercliffe Zion FC', 'ATZ', 1871, 'Attercliffe', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'from Zion Church, Attercliffe'),
('grimesthorpe-fc', 'Grimesthorpe FC', 'GRM', 1871, 'Victoria Hotel', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'Met at Victoria Hotel, Grimesthorpe'),
('exchange-brewery-fc', 'Exchange Brewery FC', 'EXB', 1871, 'Fox Street', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'played at Fox Street, Pye Bank'),
('all-saints-night-school-fc', 'All Saints Night School FC', 'ASN', 1871, 'Hall Carr Lane', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'Hall Carr Lane, now Carwood Road'),
('millhouses-fc', 'Millhouses FC', 'MLH', 1871, 'The Old Corn Mill', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'possibly played at The Old Corn Mill'),
('albion-fc', 'Albion FC', 'ALB', 1872, 'Ecclesall Road', 'Sheffield', 'Yorkshire', '#FFFFFF', '#000000', 'played at Ecclesall Road'),
('pye-bank-fc', 'Pye Bank FC', 'PYB', 1872, 'Fox Street', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'played at Fox Street, Pye Bank'),
('brightside-fc', 'Brightside FC', 'BRI', 1872, 'Blackburn Meadows', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'played at Blackburn Meadows, Blackburn'),
('norfolk-works-fc', 'Norfolk Works FC', 'NFW', 1872, 'Newhall Athletic Ground', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'Played at Newhall Athletic Ground'),
('eldon-st-judes-fc', 'Eldon St Jude''s FC', 'ESJ', 1872, 'Brocco Bank', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'played at Brocco Bank'),
('garden-street-fc', 'Garden Street FC', 'GDS', 1872, 'Hollins Crog', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'From Garden Street, Hollins Crog'),
('sharrow-rangers-fc', 'Sharrow Rangers FC', 'SHR', 1873, 'Crescent Road', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'played at Crescent Road, Sharrow'),
('endcliffe-fc', 'Endcliffe FC', 'END', 1873, 'Ecclesall Road', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'played at Ecclesall Road'),
('owlerton-fc', 'Owlerton FC', 'OWL', 1873, 'Rawson''s Meadow Ground', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'played at Rawson''s Meadow Ground, Owlerton'),
('ecclesfield-fc', 'Ecclesfield FC', 'ECF', 1873, 'Fairham''s Crog', 'Ecclesfield', 'Yorkshire', '#006400', '#FFFFFF', 'played at Fairham''s Crog'),
('philadelphia-fc', 'Philadelphia FC', 'PHI', 1873, 'Queens Ground', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'played at Queens Ground Hillsborough'),
('artillery-hallamshire-fc', 'Artillery & Hallamshire FC', 'ART', 1873, 'Endcliffe Hall', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'Based at Endcliffe Hall (later just Artillery)'),
('intake-fc', 'Intake FC', 'INT', 1873, 'Intake', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'From Intake'),
('cherrytree-fc', 'Cherrytree FC', 'CHR', 1873, 'Unknown', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'Possibly from Cherrytree Orphanage'),
('victoria-burngreave-fc', 'Victoria (Burngreave) FC', 'VIC', 1873, 'Hall Carr Lane', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'played at Hall Carr Lane, east end'),
('west-end-fc', 'West End FC', 'WST', 1873, 'Hunters Bar', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'played at Hunters Bar, from West End Hotel'),
('burys-co-fc', 'Bury''s & Co FC', 'BUR', 1873, 'Regents Works', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'From Regents Works, now Wicks'),
('beadshaws-baltic-fc', 'Beadshaw''s (Baltic) FC', 'BDB', 1873, 'Baltic Works', 'Attercliffe', 'Yorkshire', '#000080', '#FFFFFF', 'From Baltic Works, Attercliffe'),
('oughtibridge-fc', 'Oughtibridge FC', 'OUG', 1873, 'Oughtibridge', 'Oughtibridge', 'Yorkshire', '#228B22', '#FFFFFF', 'From Oughtibridge'),
('weston-fc', 'Weston FC', 'WES', 1873, 'Weston Hall', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'Possibly played at Weston Hall'),
('wardsend-steel-works-fc', 'Wardsend Steel Works FC', 'WRD', 1873, 'Herries Road', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'From Wardsend Steel Works, Herries Road'),
('owlerton-reform-fc', 'Owlerton Reform FC', 'OWR', 1873, 'Borough Road', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'From Wesleyan Reform Church on Borough Road, Owlerton'),
('roebuck-fc', 'Roebuck FC', 'ROE', 1873, 'East Bank', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'Roebuck pub, played at East Bank'),
('tennant-brothers-co-fc', 'Tennant Brothers & Co FC', 'TEN', 1873, 'Exchange Brewery', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'club from Exchange Brewery'),
('crosspool-rangers-fc', 'Crosspool Rangers FC', 'CRP', 1873, 'Crosspool', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'From Crosspool'),
('clifford-fc', 'Clifford FC', 'CLF', 1873, 'Psalter Lane', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'From Clifford House, Psalter Lane'),
('grange-fc', 'Grange FC', 'GRN', 1873, 'Intake Road', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'played at Intake Road'),
('pitsmoor-coal-company-fc', 'Pitsmoor Coal Company FC', 'PCC', 1873, 'Brightside', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'From Brightside'),
('boston-street-fc', 'Boston Street FC', 'BST', 1873, 'Heeley', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'From Boston Street, played in Heeley'),
('birley-fc', 'Birley FC', 'BIR', 1873, 'Hollinsend', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'played at Hollinsend, Birley'),
('sherrington-fc', 'Sherrington FC', 'SHE', 1873, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'From Sherrington Road, Sharrow, played Norfolk Park'),
('105th-regiment', '105th Regiment', '105', 1874, 'Unknown', 'Sheffield', 'Yorkshire', '#DC143C', '#000000', 'Joined FA in 1874. Played in FA Cup 1875 to 1879. Nickname was ''Light Bobs'''),
('carnforth-fc', 'Carnforth FC', 'CAR', 1874, 'Sharrow Vale Road', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'played at Sharrow Vale Road'),
('hollinsend-fc', 'Hollinsend FC', 'HOL', 1874, 'Unknown', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', ''),
('providence-fc', 'Providence FC', 'PRO', 1874, 'Park Hill Lane', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'played at Park Hill Lane'),
('handsworth-fc', 'Handsworth FC', 'HND', 1874, 'Unknown', 'Handsworth', 'Yorkshire', '#000080', '#FFFFFF', 'Ground unknown'),
('woodseats-fc', 'Woodseats FC', 'WDS', 1874, 'Woodseats Hotel', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'Met at the Woodseats Hotel, now Viraaj'),
('oak-street-fc', 'Oak Street FC', 'OAK', 1874, 'Heeley', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'From street of same name, Heeley'),
('atlas-fc', 'Atlas FC', 'ATL', 1874, 'Atlas Works', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'formed from Atlas Works, East End'),
('ecclesall-fc', 'Ecclesall FC', 'ECC', 1874, 'Hunters Bar', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'played at Hunters Bar'),
('nether-fc', 'Nether FC', 'NET', 1874, 'Eastborne', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'played at Eastborne'),
('broomfield-fc', 'Broomfield FC', 'BRF', 1874, 'Broomfield', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'From Broomfield area of Sheffield'),
('st-marks-fc', 'St Mark''s FC', 'STM', 1874, 'Broomfield Road', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'From St Mark''s Broomfield Road'),
('tabernacle-fc', 'Tabernacle FC', 'TAB', 1874, 'Albert Terrace Road', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'From Tabernacle Church, Albert Terrace Road'),
('st-michaels-angels-fc', 'St Michaels Angels FC', 'SMA', 1874, 'Parkwood Springs', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'From St Michael''s Church, Parkwood Springs'),
('kenwood-fc', 'Kenwood FC', 'KEN', 1874, 'Abbeydale Road', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'played at a ground off Abbeydale Road'),
('port-mahon-fc', 'Port Mahon FC', 'POR', 1874, 'Port Mahon', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'From Port Mahon, now Ponderosa'),
('st-lukes-fc', 'St Luke''s FC', 'STL', 1874, 'Park', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'From St Luke''s, Park (behind Midland Station)'),
('heeley-victoria-fc', 'Heeley Victoria FC', 'HEV', 1874, 'Victoria Hotel', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'From Victoria Hotel in Heeley'),
('shrewsbury-road-fc', 'Shrewsbury Road FC', 'SWR', 1874, 'Shrewsbury Road', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'Road of same name behind Midland station'),
('park-united-fc', 'Park United FC', 'PKU', 1874, 'Park', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'From Park area'),
('white-star-fc', 'White Star FC', 'WHT', 1874, 'Unknown', 'Sheffield', 'Yorkshire', '#FFFFFF', '#000000', 'Location origins unknown'),
('good-intent-fc', 'Good Intent FC', 'GDI', 1874, 'Truro Ground', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'Likely played at Truro Ground on Matilda Street'),
('mount-tabor-fc', 'Mount Tabor FC', 'MTB', 1874, 'City Centre', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'Church in city centre, now demolish'),
('st-judes-fc', 'St Jude''s FC', 'SJU', 1874, 'Cupola Street', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'From St Jude''s church on Cupola Street'),
('wingfield-rowbotham-fc', 'Wingfield & Rowbotham FC', 'WNR', 1874, 'Tenter Street', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'From their works on Tenter Street'),
('young-broomhall-fc', 'Young Broomhall FC', 'YBR', 1874, 'Unknown', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'Ground location unknown'),
('regents-works-fc', 'Regents Works FC', 'RGW', 1874, 'Penistone Road', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'Regents Works, now Wicks on Penistone Road'),
('lo-good-templars-fc', 'L. O. Good Templars FC', 'LGT', 1874, 'Unknown', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'Origins unknown'),
('brookes-crookes-fc', 'Brookes & Crookes FC', 'BRC', 1874, 'Brook Lane', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'From Brook Steel Works, Brook Lane'),
('polar-star-fc', 'Polar Star FC', 'POL', 1874, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'played at Norfolk Park'),
('norton-mount-view-fc', 'Norton Mount View FC', 'NMV', 1874, 'Norton Lees', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'From Mount View Methodists Church, Norton Lees'),
('mill-sands-fc', 'Mill Sands FC', 'MLS', 1874, 'Mill Sands Works', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'From Mill Sands Works, now Vulcan House'),
('fenton-brothers-fc', 'Fenton Brothers FC', 'FNB', 1874, 'East Street', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'From their works, East Street, Park'),
('sir-john-browns-fc', 'Sir John Brown''s FC', 'SJB', 1874, 'Osgathorpe', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'played at Osgathorpe, near Earl Marshall'),
('st-silas-fc', 'St Silas FC', 'STS2', 1874, 'Broomhall', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'From St Silas Church, Broomhall'),
('ecclesall-church-fc', 'Ecclesall Church FC', 'ECH', 1874, 'Ecclesall', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'From Ecclesall All Saints'),
('firths-fc', 'Firth''s FC', 'FIR2', 1874, 'East End', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'From Thomas Firth & Son''s, east end'),
('owlerton-united-fc', 'Owlerton United FC', 'OWU', 1874, 'Wadsley Bridge', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'played at Wadsley Bridge'),
('atkin-brothers-fc', 'Atkin Brothers FC', 'ATB', 1874, 'Matilda Street', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'From Truro Works, Matilda Street'),
('unitarian-fc', 'Unitarian FC', 'UNI', 1874, 'Norfolk Street', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'From Unitarian Church, Norfolk Street'),
('deep-pits-fc', 'Deep Pits FC', 'DPT', 1874, 'City Road', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'Near Manor Top, on City Road'),
('sheaf-fc', 'Sheaf FC', 'SHF2', 1874, 'Sheaf Works', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'From Sheaf Works next to Victoria station'),
('montague-fc', 'Montague FC', 'MON', 1874, 'Montague Street', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'From Montague Street Sharrow'),
('collegiate-fc', 'Collegiate FC', 'COL', 1874, 'Unknown', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', '(exact date unknown)'),
('stag-home-fc', 'Stag Home FC', 'STH', 1875, 'Kenwood', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'Origins uncertain, possibly played at Kenwood'),
('stanley-street-fc', 'Stanley Street FC', 'STS3', 1875, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'From Stanley Street, Wicker, played mainly at Norfolk Park'),
('langsett-road-fc', 'Langsett Road FC', 'LAN', 1875, 'Queens Ground', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'Likely played at Queens Ground'),
('manor-fc', 'Manor FC', 'MAN', 1875, 'Manor Lane', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'played at Manor Lane'),
('wheatman-smith-fc', 'Wheatman & Smith''s FC', 'WMS', 1875, 'Russell Works', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'From Russell Works, near Kelham Island'),
('netherthorpe-fc', 'Netherthorpe FC', 'NTH', 1875, 'Unknown', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'Ground location uncertain'),
('st-peters-fc', 'St Peter''s FC', 'STP', 1875, 'Myrtle Road', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'From the now Cathedral, played at Myrtle Road'),
('st-philips-fc', 'St Philip''s FC', 'SPH', 1875, 'Netherthorpe', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'From St Philip''s church, Netherthorpe'),
('dronfield-united-fc', 'Dronfield United FC', 'DRU', 1875, 'Dronfield', 'Dronfield', 'Yorkshire', '#FF6347', '#FFFFFF', 'From Dronfield'),
('hope-club', 'Hope Club', 'HOP', 1875, 'Weston Field', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'From Hope Works on Sussex Road, Played at Weston Field'),
('brown-bailey-dixon-fc', 'Brown Bailey & Dixon FC', 'BBD', 1875, 'Leeds Road', 'Attercliffe', 'Yorkshire', '#8B0000', '#FFFFFF', 'From their Attercliffe works, Leeds Road'),
('ward-payne-fc', 'Ward & Payne''s FC', 'WDP', 1875, 'Hillsborough', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'From their Limbrick Works, Hillsborough'),
('crookes-united-fc', 'Crookes United FC', 'CRU', 1875, 'Lydgate Lane', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'Likely played at Lydgate Lane'),
('harold-fc', 'Harold FC', 'HAR', 1875, 'Walkley', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'Likely from Harold Street, Walkley'),
('hutton-son-fc', 'Hutton & Son FC', 'HUT', 1875, 'West Street', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'From Hutton''s Works, West Street'),
('malinda-works-fc', 'Malinda Works FC', 'MAL', 1875, 'Malinda Street', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'From Malinda Works, Malinda Street'),
('parkwood-juniors-fc', 'Parkwood Juniors FC', 'PKJ', 1875, 'Parkwood Springs', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'From Parkwood Springs'),
('aston-fc', 'Aston FC', 'AST', 1875, 'Aston', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'From Aston'),
('washington-fc', 'Washington FC', 'WAS', 1875, 'Cobden View', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'From Wostenholm''s Washington Works, Washington Street, poss played at Cobden View'),
('st-pauls-fc', 'St Paul''s FC', 'SPL', 1875, 'Peace Gardens', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'From St Paul''s church, now Peace Gardens'),
('south-view-fc', 'South View FC', 'SOU', 1875, 'Machon Bank', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'From South View Road in Sharrow, played at Machon Bank'),
('ecclesall-united-fc', 'Ecclesall United FC', 'ECU', 1875, 'Ecclesall', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'played at Ecclesall'),
('msl-loco-fc', 'MS&L Loco FC', 'MSL', 1875, 'Unknown', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'Ground location unknown'),
('oxford-wanderers-fc', 'Oxford Wanderers FC', 'OXW', 1875, 'Norfolk Park', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'Poss from Oxford Street, played Norfolk Park'),
('dronfield-free-church-fc', 'Dronfield Free Church FC', 'DFC', 1875, 'High Street', 'Dronfield', 'Yorkshire', '#4169E1', '#FFFFFF', 'From Dronfield United Methodist Free Church, now Peel Centre, High Street, Dronfield'),
('atlantic-juniors-fc', 'Atlantic (Juniors) FC', 'ATJ', 1875, 'Cobden View', 'Sheffield', 'Yorkshire', '#800080', '#FFFFFF', 'played at Cobden View'),
('wincobank-fc', 'Wincobank FC', 'WIN', 1875, 'Wincobank', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'From Wincobank area'),
('alexandra-fc', 'Alexandra FC', 'ALE', 1875, 'Alexandra Road', 'Sheffield', 'Yorkshire', '#696969', '#FFFFFF', 'From Alexandra Road, Heeley'),
('carbrook-united-fc', 'Carbrook United FC', 'CBU', 1875, 'Carbrook', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'played behind St Batholowmew''s Church Carbrook'),
('r-sorby-son-fc', 'R Sorby & Son FC', 'RSO', 1875, 'Trafalgar Street', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', 'From Kangaroo Works, Trafalgar Street'),
('upperthorpe-fc', 'Upperthorpe FC', 'UPP', 1875, 'Cobden View', 'Sheffield', 'Yorkshire', '#000080', '#FFFFFF', 'played at Cobden View'),
('howard-street-fc', 'Howard Street FC', 'HOW', 1875, 'Heeley', 'Sheffield', 'Yorkshire', '#FF6347', '#FFFFFF', 'Likely played in Heeley, from Howard Street'),
('otley-sons-fc', 'Otley & Son''s FC', 'OTL', 1875, 'Shalesmoor', 'Sheffield', 'Yorkshire', '#FF4500', '#FFFFFF', 'From Meadow Works Shalesmoor'),
('hillsborough-fc', 'Hillsborough / Hillsborough School FC', 'HIL', 1875, 'Hillsborough', 'Sheffield', 'Yorkshire', '#8B0000', '#FFFFFF', 'played at Hillsborough'),
('bellefield-fc', 'Bellefield FC', 'BEL', 1875, 'Bellefield Lane', 'Sheffield', 'Yorkshire', '#DC143C', '#FFFFFF', 'From Bellefield Works, Bellefield Lane, Netherthorpe'),
('red-rose-fc', 'Red Rose FC', 'RRO', 1875, 'Unknown', 'Sheffield', 'Yorkshire', '#FF0000', '#FFFFFF', 'Could be from Pitsmoor or Bramall Lane or was possibly 2 clubs'),
('weston-rovers-fc', 'Weston Rovers FC', 'WER', 1875, 'Unknown', 'Sheffield', 'Yorkshire', '#228B22', '#FFFFFF', 'Uncertain origins'),
('j-round-son-fc', 'J Round & Son FC', 'JRS', 1875, 'Tudor Street', 'Sheffield', 'Yorkshire', '#4169E1', '#FFFFFF', 'From Tudor Works, Tudor Street, now Tudor Sq'),
('dronfield-baptists-fc', 'Dronfield Baptists FC', 'DRB', 1875, 'Stubley Lane', 'Dronfield', 'Yorkshire', '#800080', '#FFFFFF', 'From Dronfield Baptist Church, Stubley Lane'),
('pye-bank-free-church-fc', 'Pye Bank Free Church FC', 'PFC', 1875, 'Pye Bank', 'Sheffield', 'Yorkshire', '#8B4513', '#FFFFFF', 'Pye Bank, Sheffield'),
('dronfield-independent-fc', 'Dronfield Independent FC', 'DRI', 1875, 'Lea Road', 'Dronfield', 'Yorkshire', '#696969', '#FFFFFF', 'From Independent Chapel Lea Road, Dronfield'),
('ebernezer-reform-fc', 'Ebernezer Reform FC', 'EBR', 1875, 'Neepsend', 'Sheffield', 'Yorkshire', '#006400', '#FFFFFF', 'Ebernezer Chaple, Neepsend'),
('kenyons-works-fc', 'Kenyon''s Works FC', 'KNY', 1875, 'Unknown', 'Sheffield', 'Yorkshire', '#4B0082', '#FFFFFF', '');

SELECT COUNT(*) as total_clubs FROM sheffield_clubs;
