-- Clear existing clubs table
DELETE FROM sheffield_clubs;

-- Repopulate with Football clubs 1857 to 1875
-- Format: id, name, founded_year, ground_name, city, region, origin

INSERT INTO sheffield_clubs (id, name, founded_year, ground_name, city, region, origin) VALUES
('sheffield-fc', 'Sheffield FC', 1857, 'East Bank', 'Sheffield', 'Sheffield', 'played at East Bank'),
('hallam-fc', 'Hallam FC', 1860, 'Sandygate', 'Sheffield', 'Sheffield', 'play at Sandygate'),
('norfolk-fc', 'Norfolk FC', 1861, 'Norfolk Park', 'Sheffield', 'Sheffield', 'played at Norfolk Park'),
('cemetery-road-church-fc', 'Cemetery Road Church FC', 1861, 'Hunters Bar', 'Sheffield', 'Sheffield', 'Oldest church club, played at Hunters Bar'),
('york-fc', 'York FC', 1861, 'Endcliffe Cricket Ground', 'Sheffield', 'Sheffield', 'From York Hotel, Broomhill, played at Endcliffe Cricket Ground, N Creswick was President'),
('norton-fc', 'Norton FC', 1861, 'Oaks Park, Norton', 'Sheffield', 'Sheffield', 'played at Oaks Park, Norton'),
('pitsmoor-fc', 'Pitsmoor FC', 1861, 'Pitsmoor CC', 'Sheffield', 'Sheffield', 'played at Pitsmoor CC, now SUFC Academy'),
('fir-vale-fc', 'Fir Vale FC', 1862, 'Pitsmoor CC', 'Sheffield', 'Sheffield', 'played at Pitsmoor CC, now SUFC Academy'),
('heeley-christ-church-fc', 'Heeley Christ Church FC', 1862, 'Meersbrook Park', 'Sheffield', 'Sheffield', 'played at Meersbrook Park'),
('mackenzie-fc', 'Mackenzie FC', 1862, 'Myrtle Road, Heeley', 'Sheffield', 'Sheffield', 'played at Myrtle Road, Heeley'),
('milton-fc', 'Milton FC', 1862, 'Cremorne Gardens, London Road', 'Sheffield', 'Sheffield', 'played at Cremorne Gardens, London Road'),
('howard-hill-steel-bank-fc', 'Howard Hill Steel Bank FC', 1862, 'Unknown', 'Sheffield', 'Sheffield', 'Met in Howard Hotel, Howard Road'),
('ranmoor-fc', 'Ranmoor FC', 1862, 'Ranmoor', 'Sheffield', 'Sheffield', 'played in Ranmoor'),
('st-george-fc', 'St George FC', 1862, 'Unknown', 'Sheffield', 'Sheffield', 'From St George''s Church, Broad Lane'),
('st-stephen-fc', 'St Stephen FC', 1862, 'Crookes', 'Sheffield', 'Sheffield', 'From St Stephen''s Church Fawcett Road Netherthorpe. Played at Crookes'),
('united-norfolk-fc', 'United Norfolk FC', 1862, 'Unknown', 'Sheffield', 'Sheffield', 'Origins uncertain'),
('crabtree-fc', 'Crabtree FC', 1863, 'Unknown', 'Sheffield', 'Sheffield', 'Likely from Fir Vale area'),
('broomhall-fc', 'Broomhall FC', 1863, 'Ecclesall Road', 'Sheffield', 'Sheffield', 'played at Ecclesall Road'),
('tudor-fc', 'Tudor FC', 1863, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('wh-hutchinson-fc', 'W & H Hutchinson''s FC', 1863, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('hemsworth-fc', 'Hemsworth FC', 1863, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('united-mechanics', 'United Mechanics', 1865, 'Norfolk Park', 'Sheffield', 'Sheffield', 'played at Norfolk Park'),
('garrick-fc', 'Garrick FC', 1866, 'East Bank', 'Sheffield', 'Sheffield', 'played at East Bank'),
('wellington-fc', 'Wellington FC', 1866, 'Hounsfield Park', 'Sheffield', 'Sheffield', 'played at Hounsfield Park near Bramall Lane'),
('loxley-fc', 'Loxley FC', 1866, 'Unknown', 'Sheffield', 'Sheffield', 'Met at The Rodney Inn, Loxley'),
('wednesday-fc', 'Wednesday FC', 1867, 'Highfields', 'Sheffield', 'Sheffield', 'played at Highfields, now Hillsborough'),
('exchange-fc', 'Exchange FC', 1867, 'Hallam''s Farm', 'Sheffield', 'Sheffield', 'played at Hallam''s Farm, now Hyde Park Flats'),
('dore-fc', 'Dore FC', 1867, 'Unknown', 'Sheffield', 'Sheffield', 'Met at The Devonshire Arms, Dore'),
('tapton-fc', 'Tapton FC', 1867, 'Tapton Hall', 'Sheffield', 'Sheffield', 'Based at Tapton Hall'),
('dronfield-fc', 'Dronfield FC', 1868, 'Bagley''s Field', 'Dronfield', 'Derbyshire', 'played at Bagley''s Field, Dronfield'),
('parkwood-springs-fc', 'Parkwood Springs FC', 1869, 'Parkwood Springs Recreation Ground', 'Sheffield', 'Sheffield', 'played at Parkwood Springs Recreation Ground'),
('brincliffe-fc', 'Brincliffe FC', 1868, 'Cherry Tree Farm', 'Sheffield', 'Sheffield', 'played at Cherry Tree Farm, near Union pub'),
('hanover-united-fc', 'Hanover United FC', 1868, 'Crookes', 'Sheffield', 'Sheffield', 'played at Crookes'),
('stannington-fc', 'Stannington FC', 1868, 'Unknown', 'Sheffield', 'Sheffield', 'unknown ground location'),
('redhill-fc', 'Redhill FC', 1868, 'Winter Street', 'Sheffield', 'Sheffield', 'played at Winter Street, near Weston Park'),
('oxford-fc', 'Oxford FC', 1869, 'Ecclesall Road', 'Sheffield', 'Sheffield', 'played at Ecclesall Road'),
('totley-fc', 'Totley FC', 1869, 'Cross Scythes Inn', 'Sheffield', 'Sheffield', 'played at field next to Cross Scythes Inn, Totley'),
('sheffield-norfolk-fc', 'Sheffield Norfolk FC', 1869, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('st-vincents', 'St Vincent''s', 1869, 'Queens Ground', 'Sheffield', 'Sheffield', 'from Solly Street – played at Queens Ground'),
('st-james-church-fc', 'St James Church FC', 1869, 'Norton Lees Lane', 'Sheffield', 'Sheffield', 'played at Norton Lees Lane'),
('lockwood-brothers-fc', 'Lockwood Brothers FC', 1870, 'Hunters Bar', 'Sheffield', 'Sheffield', 'played at Hunters Bar, oldest works club'),
('talbot-fc', 'Talbot FC', 1870, 'Norfolk Road', 'Sheffield', 'Sheffield', 'played at Norfolk Road'),
('sheffield-united-gymnastic-club', 'Sheffield United Gymnastic Club', 1870, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('ecclesall-college-fc', 'Ecclesall College FC', 1870, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('sheffield-grammar-school-fc', 'Sheffield Grammar School FC', 1870, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('surrey-catholic-club', 'Surrey Catholic Club', 1870, 'The Farm', 'Sheffield', 'Sheffield', 'played at The Farm, now Sheffield College'),
('attercliffe-christ-church', 'Attercliffe (Christ Church)', 1870, 'The Old Forge Ground', 'Sheffield', 'Sheffield', 'played at The Old Forge Ground, Shirland Lane'),
('walkley-new-connexion-fc', 'Walkley New Connexion FC', 1870, 'Queens Ground', 'Sheffield', 'Sheffield', 'played at Queens Ground, Hillsborough'),
('crookes-fc', 'Crookes FC', 1870, 'Lydgate Lane', 'Sheffield', 'Sheffield', 'played at Lydgate Lane'),
('bankers-thursday', 'Bankers / Thursday', 1870, 'Hunters Bar', 'Sheffield', 'Sheffield', 'played at Hunters Bar'),
('alliance-fc', 'Alliance FC', 1870, 'Norfolk Park', 'Sheffield', 'Sheffield', 'played at Norfolk Park'),
('perseverance-fc', 'Perseverance FC', 1870, 'Norfolk Park', 'Sheffield', 'Sheffield', 'played at Norfolk Park'),
('gleadless-fc', 'Gleadless FC', 1870, 'Charnock Hall', 'Sheffield', 'Sheffield', 'played at Charnock Hall, Gleadless'),
('engineers-fc', 'Engineers FC', 1870, 'Endcliffe Crescent', 'Sheffield', 'Sheffield', 'Played at Endcliffe Crescent'),
('attercliffe-zion-fc', 'Attercliffe Zion FC', 1871, 'Unknown', 'Sheffield', 'Sheffield', 'from Zion Church, Attercliffe'),
('grimesthorpe-fc', 'Grimesthorpe FC', 1871, 'Unknown', 'Sheffield', 'Sheffield', 'Met at Victoria Hotel, Grimesthorpe'),
('exchange-brewery-fc', 'Exchange Brewery FC', 1871, 'Fox Street, Pye Bank', 'Sheffield', 'Sheffield', 'played at Fox Street, Pye Bank'),
('all-saints-night-school-fc', 'All Saints Night School FC', 1871, 'Hall Carr Lane', 'Sheffield', 'Sheffield', 'Hall Carr Lane, now Carwood Road'),
('millhouses-fc', 'Millhouses FC', 1871, 'The Old Corn Mill', 'Sheffield', 'Sheffield', 'possibly played at The Old Corn Mill'),
('albion-fc', 'Albion FC', 1872, 'Ecclesall Road', 'Sheffield', 'Sheffield', 'played at Ecclesall Road'),
('pye-bank-fc', 'Pye Bank FC', 1872, 'Fox Street, Pye Bank', 'Sheffield', 'Sheffield', 'played at Fox Street, Pye Bank'),
('brightside-fc', 'Brightside FC', 1872, 'Blackburn Meadows', 'Sheffield', 'Sheffield', 'played at Blackburn Meadows, Blackburn'),
('norfolk-works-fc', 'Norfolk Works FC', 1872, 'Newhall Athletic Ground', 'Sheffield', 'Sheffield', 'Played at Newhall Athletic Ground'),
('eldon-st-judes-fc', 'Eldon St Jude''s FC', 1872, 'Brocco Bank', 'Sheffield', 'Sheffield', 'played at Brocco Bank'),
('garden-street-fc', 'Garden Street FC', 1872, 'Unknown', 'Sheffield', 'Sheffield', 'From Garden Street, Hollins Crog'),
('sharrow-rangers-fc', 'Sharrow Rangers FC', 1873, 'Crescent Road, Sharrow', 'Sheffield', 'Sheffield', 'played at Crescent Road, Sharrow'),
('endcliffe-fc', 'Endcliffe FC', 1873, 'Ecclesall Road', 'Sheffield', 'Sheffield', 'played at Ecclesall Road'),
('owlerton-fc', 'Owlerton FC', 1873, 'Rawson''s Meadow Ground', 'Sheffield', 'Sheffield', 'played at Rawson''s Meadow Ground, Owlerton'),
('ecclesfield-fc', 'Ecclesfield FC', 1873, 'Fairham''s Crog', 'Sheffield', 'Sheffield', 'played at Fairham''s Crog'),
('philadelphia-fc', 'Philadelphia FC', 1873, 'Queens Ground Hillsborough', 'Sheffield', 'Sheffield', 'played at Queens Ground Hillsborough'),
('artillery-hallamshire-fc', 'Artillery & Hallamshire FC', 1873, 'Endcliffe Hall', 'Sheffield', 'Sheffield', 'Based at Endcliffe Hall (later just Artillery)'),
('intake-fc', 'Intake FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Intake'),
('cherrytree-fc', 'Cherrytree FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'Possibly from Cherrytree Orphanage'),
('victoria-burngreave-fc', 'Victoria (Burngreave) FC', 1873, 'Hall Carr Lane', 'Sheffield', 'Sheffield', 'played at Hall Carr Lane, east end'),
('west-end-fc', 'West End FC', 1873, 'Hunters Bar', 'Sheffield', 'Sheffield', 'played at Hunters Bar, from West End Hotel'),
('burys-co-fc', 'Bury''s & Co FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Regents Works, now Wicks'),
('beadshaws-baltic-fc', 'Beadshaw''s (Baltic) FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Baltic Works, Attercliffe'),
('oughtibridge-fc', 'Oughtibridge FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Oughtibridge'),
('weston-fc', 'Weston FC', 1873, 'Weston Hall', 'Sheffield', 'Sheffield', 'Possibly played at Weston Hall'),
('wardsend-steel-works-fc', 'Wardsend Steel Works FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Wardsend Steel Works, Herries Road'),
('owlerton-reform-fc', 'Owlerton Reform FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Wesleyan Reform Church on Borough Road, Owlerton'),
('roebuck-fc', 'Roebuck FC', 1873, 'East Bank', 'Sheffield', 'Sheffield', 'Roebuck pub, played at East Bank'),
('tennant-brothers-co-fc', 'Tennant Brothers & Co FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'club from Exchange Brewery'),
('crosspool-rangers-fc', 'Crosspool Rangers FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Crosspool'),
('clifford-fc', 'Clifford FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Clifford House, Psalter Lane'),
('grange-fc', 'Grange FC', 1873, 'Intake Road', 'Sheffield', 'Sheffield', 'played at Intake Road'),
('pitsmoor-coal-company-fc', 'Pitsmoor Coal Company FC', 1873, 'Unknown', 'Sheffield', 'Sheffield', 'From Brightside'),
('boston-street-fc', 'Boston Street FC', 1873, 'Heeley', 'Sheffield', 'Sheffield', 'From Boston Street, played in Heeley'),
('birley-fc', 'Birley FC', 1873, 'Hollinsend', 'Sheffield', 'Sheffield', 'played at Hollinsend, Birley'),
('sherrington-fc', 'Sherrington FC', 1873, 'Norfolk Park', 'Sheffield', 'Sheffield', 'From Sherrington Road, Sharrow, played Norfolk Park'),
('105th-regiment', '105th Regiment', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Joined FA in 1874. Played in FA Cup 1875 to 1879. Nickname was ''Light Bobs'''),
('carnforth-fc', 'Carnforth FC', 1874, 'Sharrow Vale Road', 'Sheffield', 'Sheffield', 'played at Sharrow Vale Road'),
('hollinsend-fc', 'Hollinsend FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', NULL),
('providence-fc', 'Providence FC', 1874, 'Park Hill Lane', 'Sheffield', 'Sheffield', 'played at Park Hill Lane'),
('handsworth-fc', 'Handsworth FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Ground unknown'),
('woodseats-fc', 'Woodseats FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Met at the Woodseats Hotel, now Viraaj'),
('oak-street-fc', 'Oak Street FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From street of same name, Heeley'),
('atlas-fc', 'Atlas FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'formed from Atlas Works, East End'),
('ecclesall-fc', 'Ecclesall FC', 1874, 'Hunters Bar', 'Sheffield', 'Sheffield', 'played at Hunters Bar'),
('nether-fc', 'Nether FC', 1874, 'Eastborne', 'Sheffield', 'Sheffield', 'played at Eastborne'),
('broomfield-fc', 'Broomfield FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Broomfield area of Sheffield'),
('st-marks-fc', 'St Mark''s FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From St Mark''s Broomfield Road'),
('tabernacle-fc', 'Tabernacle FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Tabernacle Church, Albert Terrace Road'),
('st-michaels-angels-fc', 'St Michaels Angels FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From St Michael''s Church, Parkwood Springs'),
('kenwood-fc', 'Kenwood FC', 1874, 'Abbeydale Road', 'Sheffield', 'Sheffield', 'played at a ground off Abbeydale Road'),
('port-mahon-fc', 'Port Mahon FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Port Mahon, now Ponderosa'),
('st-lukes-fc', 'St Luke''s FC', 1874, 'Park', 'Sheffield', 'Sheffield', 'From St Luke''s, Park (behind Midland Station)'),
('heeley-victoria-fc', 'Heeley Victoria FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Victoria Hotel in Heeley'),
('shrewsbury-road-fc', 'Shrewsbury Road FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Road of same name behind Midland station'),
('park-united-fc', 'Park United FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Park area'),
('white-star-fc', 'White Star FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Location origins unknown'),
('good-intent-fc', 'Good Intent FC', 1874, 'Truro Ground', 'Sheffield', 'Sheffield', 'Likely played at Truro Ground on Matilda Street'),
('mount-tabor-fc', 'Mount Tabor FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Church in city centre, now demolished'),
('st-judes-fc', 'St Jude''s FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From St Jude''s church on Cupola Street'),
('wingfield-rowbotham-fc', 'Wingfield & Rowbotham FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From their works on Tenter Street'),
('young-broomhall-fc', 'Young Broomhall FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Ground location unknown'),
('regents-works-fc', 'Regents Works FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Regents Works, now Wicks on Penistone Road'),
('lo-good-templars-fc', 'L. O. Good Templars FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'Origins unknown'),
('brookes-crookes-fc', 'Brookes & Crookes FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Brook Steel Works, Brook Lane'),
('polar-star-fc', 'Polar Star FC', 1874, 'Norfolk Park', 'Sheffield', 'Sheffield', 'played at Norfolk Park'),
('norton-mount-view-fc', 'Norton Mount View FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Mount View Methodists Church, Norton Lees'),
('mill-sands-fc', 'Mill Sands FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Mill Sands Works, now Vulcan House'),
('fenton-brothers-fc', 'Fenton Brothers FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From their works, East Street, Park'),
('sir-john-browns-fc', 'Sir John Brown''s FC', 1874, 'Osgathorpe', 'Sheffield', 'Sheffield', 'played at Osgathorpe, near Earl Marshall'),
('st-silas-fc', 'St Silas FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From St Silas Church, Broomhall'),
('ecclesall-church-fc', 'Ecclesall Church FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Ecclesall All Saints'),
('firths-fc', 'Firth''s FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Thomas Firth & Son''s, east end'),
('owlerton-united-fc', 'Owlerton United FC', 1874, 'Wadsley Bridge', 'Sheffield', 'Sheffield', 'played at Wadsley Bridge'),
('atkin-brothers-fc', 'Atkin Brothers FC', 1874, 'Truro Works', 'Sheffield', 'Sheffield', 'From Truro Works, Matilda Street'),
('unitarian-fc', 'Unitarian FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Unitarian Church, Norfolk Street'),
('deep-pits-fc', 'Deep Pits FC', 1874, 'City Road', 'Sheffield', 'Sheffield', 'Near Manor Top, on City Road'),
('sheaf-fc', 'Sheaf FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Sheaf Works next to Victoria station'),
('montague-fc', 'Montague FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'From Montague Street Sharrow'),
('collegiate-fc', 'Collegiate FC', 1874, 'Unknown', 'Sheffield', 'Sheffield', 'exact date unknown'),
('stag-home-fc', 'Stag Home FC', 1875, 'Kenwood', 'Sheffield', 'Sheffield', 'Origins uncertain, possibly played at Kenwood'),
('stanley-street-fc', 'Stanley Street FC', 1875, 'Norfolk Park', 'Sheffield', 'Sheffield', 'From Stanley Street, Wicker, played mainly at Norfolk Park'),
('langsett-road-fc', 'Langsett Road FC', 1875, 'Queens Ground', 'Sheffield', 'Sheffield', 'Likely played at Queens Ground'),
('manor-fc', 'Manor FC', 1875, 'Manor Lane', 'Sheffield', 'Sheffield', 'played at Manor Lane'),
('wheatman-smiths-fc', 'Wheatman & Smith''s FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Russell Works, near Kelham Island'),
('netherthorpe-fc', 'Netherthorpe FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'Ground location uncertain'),
('st-peters-fc', 'St Peter''s FC', 1875, 'Myrtle Road', 'Sheffield', 'Sheffield', 'From the now Cathedral, played at Myrtle Road'),
('st-philips-fc', 'St Philip''s FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From St Philip''s church, Netherthorpe'),
('dronfield-united-fc', 'Dronfield United FC', 1875, 'Unknown', 'Dronfield', 'Derbyshire', 'From Dronfield'),
('hope-club', 'Hope Club', 1875, 'Weston Field', 'Sheffield', 'Sheffield', 'From Hope Works on Sussex Road, Played at Weston Field'),
('brown-bailey-dixon-fc', 'Brown Bailey & Dixon FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From their Attercliffe works, Leeds Road'),
('ward-paynes-fc', 'Ward & Payne''s FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From their Limbrick Works, Hillsborough'),
('crookes-united-fc', 'Crookes United FC', 1875, 'Lydgate Lane', 'Sheffield', 'Sheffield', 'Likely played at Lydgate Lane'),
('harold-fc', 'Harold FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'Likely from Harold Street, Walkley'),
('hutton-son-fc', 'Hutton & Son FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Hutton''s Works, West Street'),
('malinda-works-fc', 'Malinda Works FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Malinda Works, Malinda Street'),
('parkwood-juniors-fc', 'Parkwood Juniors FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Parkwood Springs'),
('aston-fc', 'Aston FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Aston'),
('washington-fc', 'Washington FC', 1875, 'Cobden View', 'Sheffield', 'Sheffield', 'From Wostenholm''s Washington Works, Washington Street, poss played at Cobden View'),
('st-pauls-fc', 'St Paul''s FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From St Paul''s church, now Peace Gardens'),
('south-view-fc', 'South View FC', 1875, 'Machon Bank', 'Sheffield', 'Sheffield', 'From South View Road in Sharrow, played at Machon Bank'),
('ecclesall-united-fc', 'Ecclesall United FC', 1875, 'Ecclesall', 'Sheffield', 'Sheffield', 'played at Ecclesall'),
('msl-loco-fc', 'MS&L Loco FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'Ground location unknown'),
('oxford-wanderers-fc', 'Oxford Wanderers FC', 1875, 'Norfolk Park', 'Sheffield', 'Sheffield', 'Poss from Oxford Street, played Norfolk Park'),
('dronfield-free-church-fc', 'Dronfield Free Church FC', 1875, 'Unknown', 'Dronfield', 'Derbyshire', 'From Dronfield United Methodist Free Church, now Peel Centre, High Street, Dronfield'),
('atlantic-juniors-fc', 'Atlantic (Juniors) FC', 1875, 'Cobden View', 'Sheffield', 'Sheffield', 'played at Cobden View'),
('wincobank-fc', 'Wincobank FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Wincobank area'),
('alexandra-fc', 'Alexandra FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Alexandra Road, Heeley'),
('carbrook-united-fc', 'Carbrook United FC', 1875, 'Behind St Batholowmew''s Church', 'Sheffield', 'Sheffield', 'played behind St Batholowmew''s Church Carbrook'),
('r-sorby-son-fc', 'R Sorby & Son FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Kangaroo Works, Trafalgar Street'),
('upperthorpe-fc', 'Upperthorpe FC', 1875, 'Cobden View', 'Sheffield', 'Sheffield', 'played at Cobden View'),
('howard-street-fc', 'Howard Street FC', 1875, 'Heeley', 'Sheffield', 'Sheffield', 'Likely played in Heeley, from Howard Street'),
('otley-sons-fc', 'Otley & Son''s FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Meadow Works Shalesmoor'),
('hillsborough-fc', 'Hillsborough / Hillsborough School FC', 1875, 'Hillsborough', 'Sheffield', 'Sheffield', 'played at Hillsborough'),
('bellefield-fc', 'Bellefield FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Bellefield Works, Bellefield Lane, Netherthorpe'),
('red-rose-fc', 'Red Rose FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'Could be from Pitsmoor or Bramall Lane or was possibly 2 clubs'),
('weston-rovers-fc', 'Weston Rovers FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'Uncertain origins'),
('j-round-son-fc', 'J Round & Son FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'From Tudor Works, Tudor Street, now Tudor Sq'),
('dronfield-baptists-fc', 'Dronfield Baptists FC', 1875, 'Unknown', 'Dronfield', 'Derbyshire', 'From Dronfield Baptist Church, Stubley Lane'),
('pye-bank-free-church-fc', 'Pye Bank Free Church FC', 1875, 'Pye Bank', 'Sheffield', 'Sheffield', 'Pye Bank, Sheffield'),
('dronfield-independent-fc', 'Dronfield Independent FC', 1875, 'Unknown', 'Dronfield', 'Derbyshire', 'From Independent Chapel Lea Road, Dronfield'),
('ebernezer-reform-fc', 'Ebernezer Reform FC', 1875, 'Unknown', 'Sheffield', 'Sheffield', 'Ebernezer Chapel, Netherthorpe');
