UPDATE unmatched_genealogy SET postcode = 'S3 7NJ' WHERE rowid = 61695;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 61696;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61698;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61699;
UPDATE unmatched_genealogy SET postcode = 'S1 2BS' WHERE rowid = 61703;
UPDATE unmatched_genealogy SET postcode = 'S1 2JB' WHERE rowid = 61704;
UPDATE unmatched_genealogy SET postcode = 'S1 2NG' WHERE rowid = 61705;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61706;
UPDATE unmatched_genealogy SET postcode = 'S2 5QA' WHERE rowid = 61721;
UPDATE unmatched_genealogy SET postcode = 'S3 7SD' WHERE rowid = 61733;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 61734;
UPDATE unmatched_genealogy SET postcode = 'S1 2DH' WHERE rowid = 61736;
UPDATE unmatched_genealogy SET postcode = 'S3 8NW' WHERE rowid = 61737;
UPDATE unmatched_genealogy SET postcode = 'S3 8NW' WHERE rowid = 61738;
UPDATE unmatched_genealogy SET postcode = 'S4 8AD' WHERE rowid = 61741;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 61742;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 61743;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 61747;
UPDATE unmatched_genealogy SET postcode = 'S9 3FF' WHERE rowid = 61751;
UPDATE unmatched_genealogy SET postcode = 'S2 4AF' WHERE rowid = 61755;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61762;
UPDATE unmatched_genealogy SET postcode = 'S3 8LT' WHERE rowid = 61767;
UPDATE unmatched_genealogy SET postcode = 'S3 7PH' WHERE rowid = 61774;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61775;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 61778;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 61788;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61796;
UPDATE unmatched_genealogy SET postcode = 'S6 1WR' WHERE rowid = 61801;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 61804;
UPDATE unmatched_genealogy SET postcode = 'S17' WHERE rowid = 61809;
UPDATE unmatched_genealogy SET postcode = 'S1 1GN' WHERE rowid = 61827;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61830;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 61832;
UPDATE unmatched_genealogy SET postcode = 'S4 7AB' WHERE rowid = 61834;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61846;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61847;
UPDATE unmatched_genealogy SET postcode = 'S11 7EU' WHERE rowid = 61848;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61856;
UPDATE unmatched_genealogy SET postcode = 'S2 2TN' WHERE rowid = 61859;
UPDATE unmatched_genealogy SET postcode = 'S3 8DB' WHERE rowid = 61865;
UPDATE unmatched_genealogy SET postcode = 'S11 8HF' WHERE rowid = 61866;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 61870;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 61872;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61874;
UPDATE unmatched_genealogy SET postcode = 'S12 2LG' WHERE rowid = 61877;
UPDATE unmatched_genealogy SET postcode = 'S7 1NP' WHERE rowid = 61883;
UPDATE unmatched_genealogy SET postcode = 'S3 7RW' WHERE rowid = 61896;
UPDATE unmatched_genealogy SET postcode = 'S3 8EA' WHERE rowid = 61899;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 61906;
UPDATE unmatched_genealogy SET postcode = 'S3 7PP' WHERE rowid = 61913;
UPDATE unmatched_genealogy SET postcode = 'S4 8AD' WHERE rowid = 61914;
UPDATE unmatched_genealogy SET postcode = 'S1 2GA' WHERE rowid = 61915;
UPDATE unmatched_genealogy SET postcode = 'S4 8DQ' WHERE rowid = 61918;
UPDATE unmatched_genealogy SET postcode = 'S3 7EQ' WHERE rowid = 61919;
UPDATE unmatched_genealogy SET postcode = 'S3 7AA' WHERE rowid = 61924;
UPDATE unmatched_genealogy SET postcode = 'S3 7ES' WHERE rowid = 61927;
UPDATE unmatched_genealogy SET postcode = 'S6 1WR' WHERE rowid = 61932;
UPDATE unmatched_genealogy SET postcode = 'S9 5AB' WHERE rowid = 61935;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 61936;
UPDATE unmatched_genealogy SET postcode = 'S13 9XA' WHERE rowid = 61946;
UPDATE unmatched_genealogy SET postcode = 'S9 2FZ' WHERE rowid = 61948;
UPDATE unmatched_genealogy SET postcode = 'S9 2FZ' WHERE rowid = 61949;
UPDATE unmatched_genealogy SET postcode = 'S4 7HA' WHERE rowid = 61958;
UPDATE unmatched_genealogy SET postcode = 'S4 7HA' WHERE rowid = 61959;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 61963;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 61968;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 61971;
UPDATE unmatched_genealogy SET postcode = 'S35' WHERE rowid = 61972;
UPDATE unmatched_genealogy SET postcode = 'S10 1GA' WHERE rowid = 61973;
UPDATE unmatched_genealogy SET postcode = 'S3 8LX' WHERE rowid = 61975;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 61978;
UPDATE unmatched_genealogy SET postcode = 'S4 8AD' WHERE rowid = 61979;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 61980;
UPDATE unmatched_genealogy SET postcode = 'S10 2PH' WHERE rowid = 61982;
UPDATE unmatched_genealogy SET postcode = 'S10 1GA' WHERE rowid = 61991;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 61994;
UPDATE unmatched_genealogy SET postcode = 'S9 3FF' WHERE rowid = 61995;
UPDATE unmatched_genealogy SET postcode = 'S3 9HA' WHERE rowid = 61997;
UPDATE unmatched_genealogy SET postcode = 'S4 7LJ' WHERE rowid = 62012;
UPDATE unmatched_genealogy SET postcode = 'S3 7AD' WHERE rowid = 62013;
UPDATE unmatched_genealogy SET postcode = 'S1 2GA' WHERE rowid = 62016;
UPDATE unmatched_genealogy SET postcode = 'S1 4GE' WHERE rowid = 62025;
UPDATE unmatched_genealogy SET postcode = 'S3 8NS' WHERE rowid = 62027;
UPDATE unmatched_genealogy SET postcode = 'S10 5NT' WHERE rowid = 62028;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62031;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62032;
UPDATE unmatched_genealogy SET postcode = 'S13 7PG' WHERE rowid = 62036;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62037;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 62039;
UPDATE unmatched_genealogy SET postcode = 'S2 5PU' WHERE rowid = 62046;
UPDATE unmatched_genealogy SET postcode = 'S3 8LX' WHERE rowid = 62051;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 62052;
UPDATE unmatched_genealogy SET postcode = 'S10 5NT' WHERE rowid = 62054;
UPDATE unmatched_genealogy SET postcode = 'S3 8RW' WHERE rowid = 62055;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 62060;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 62062;
UPDATE unmatched_genealogy SET postcode = 'S3 7PA' WHERE rowid = 62063;
UPDATE unmatched_genealogy SET postcode = 'S6' WHERE rowid = 62070;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62071;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62074;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 62076;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62093;
UPDATE unmatched_genealogy SET postcode = 'S3 7AD' WHERE rowid = 62094;
UPDATE unmatched_genealogy SET postcode = 'S6 3AA' WHERE rowid = 62099;
UPDATE unmatched_genealogy SET postcode = 'S17' WHERE rowid = 62108;
UPDATE unmatched_genealogy SET postcode = 'S11 8FJ' WHERE rowid = 62112;
UPDATE unmatched_genealogy SET postcode = 'S4 7PS' WHERE rowid = 62116;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62118;
UPDATE unmatched_genealogy SET postcode = 'S9 3JA' WHERE rowid = 62142;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62145;
UPDATE unmatched_genealogy SET postcode = 'S4 7WA' WHERE rowid = 62148;
UPDATE unmatched_genealogy SET postcode = 'S3 7NW' WHERE rowid = 62150;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 62155;
UPDATE unmatched_genealogy SET postcode = 'S1 4BA' WHERE rowid = 62157;
UPDATE unmatched_genealogy SET postcode = 'S1 2HD' WHERE rowid = 62158;
UPDATE unmatched_genealogy SET postcode = 'S3 7AA' WHERE rowid = 62159;
UPDATE unmatched_genealogy SET postcode = 'S2 5QA' WHERE rowid = 62161;
UPDATE unmatched_genealogy SET postcode = 'S6 3BT' WHERE rowid = 62174;
UPDATE unmatched_genealogy SET postcode = 'S1 2GQ' WHERE rowid = 62176;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62186;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62194;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62206;
UPDATE unmatched_genealogy SET postcode = 'S1 4EA' WHERE rowid = 62209;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 62213;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 62214;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62215;
UPDATE unmatched_genealogy SET postcode = 'S3 7AA' WHERE rowid = 62216;
UPDATE unmatched_genealogy SET postcode = 'S3 7BA' WHERE rowid = 62218;
UPDATE unmatched_genealogy SET postcode = 'S3 7BA' WHERE rowid = 62219;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62224;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62226;
UPDATE unmatched_genealogy SET postcode = 'S3 7EQ' WHERE rowid = 62227;
UPDATE unmatched_genealogy SET postcode = 'S4 8AD' WHERE rowid = 62228;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62229;
UPDATE unmatched_genealogy SET postcode = 'S3 7JN' WHERE rowid = 62232;
UPDATE unmatched_genealogy SET postcode = 'S3 7AD' WHERE rowid = 62234;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 62237;
UPDATE unmatched_genealogy SET postcode = 'S3 7PH' WHERE rowid = 62238;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62242;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62243;
UPDATE unmatched_genealogy SET postcode = 'S1 4BS' WHERE rowid = 62245;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 62246;
UPDATE unmatched_genealogy SET postcode = 'S1 4BA' WHERE rowid = 62247;
UPDATE unmatched_genealogy SET postcode = 'S1 4BA' WHERE rowid = 62248;
UPDATE unmatched_genealogy SET postcode = 'S3 7NJ' WHERE rowid = 62252;
UPDATE unmatched_genealogy SET postcode = 'S3 8BW' WHERE rowid = 62253;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 62254;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 62255;
UPDATE unmatched_genealogy SET postcode = 'S3 7NQ' WHERE rowid = 62259;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62260;
UPDATE unmatched_genealogy SET postcode = 'S1 2JB' WHERE rowid = 62263;
UPDATE unmatched_genealogy SET postcode = 'S1 2BS' WHERE rowid = 62264;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62266;
UPDATE unmatched_genealogy SET postcode = 'S1 2GH' WHERE rowid = 62270;
UPDATE unmatched_genealogy SET postcode = 'S1 2AT' WHERE rowid = 62277;
UPDATE unmatched_genealogy SET postcode = 'S1 2BG' WHERE rowid = 62279;
UPDATE unmatched_genealogy SET postcode = 'S1 2BG' WHERE rowid = 62280;
UPDATE unmatched_genealogy SET postcode = 'S1 4RD' WHERE rowid = 62282;
UPDATE unmatched_genealogy SET postcode = 'S2 5AT' WHERE rowid = 62287;
UPDATE unmatched_genealogy SET postcode = 'S3 7PH' WHERE rowid = 62295;
UPDATE unmatched_genealogy SET postcode = 'S10 1GA' WHERE rowid = 62296;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62300;
UPDATE unmatched_genealogy SET postcode = 'S10 5DF' WHERE rowid = 62301;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62302;
UPDATE unmatched_genealogy SET postcode = 'S2 2TN' WHERE rowid = 62305;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62308;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62323;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62325;
UPDATE unmatched_genealogy SET postcode = 'S1 4EA' WHERE rowid = 62326;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62327;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 62332;
UPDATE unmatched_genealogy SET postcode = 'S3 7BA' WHERE rowid = 62334;
UPDATE unmatched_genealogy SET postcode = 'S3 7BA' WHERE rowid = 62335;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 62336;
UPDATE unmatched_genealogy SET postcode = 'S1 2GH' WHERE rowid = 62337;
UPDATE unmatched_genealogy SET postcode = 'S1 4BA' WHERE rowid = 62342;
UPDATE unmatched_genealogy SET postcode = 'S3 8BW' WHERE rowid = 62344;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62346;
UPDATE unmatched_genealogy SET postcode = 'S3 7NW' WHERE rowid = 62347;
UPDATE unmatched_genealogy SET postcode = 'S6 3BT' WHERE rowid = 62348;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62356;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62357;
UPDATE unmatched_genealogy SET postcode = 'S1 2PF' WHERE rowid = 62359;
UPDATE unmatched_genealogy SET postcode = 'S1 2AT' WHERE rowid = 62363;
UPDATE unmatched_genealogy SET postcode = 'S2 4AF' WHERE rowid = 62365;
UPDATE unmatched_genealogy SET postcode = 'S1 2DH' WHERE rowid = 62371;
UPDATE unmatched_genealogy SET postcode = 'S1 2GQ' WHERE rowid = 62381;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 62384;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 62390;
UPDATE unmatched_genealogy SET postcode = 'S1 2GA' WHERE rowid = 62400;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62413;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62447;
UPDATE unmatched_genealogy SET postcode = 'S6 3DN' WHERE rowid = 62451;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62453;
UPDATE unmatched_genealogy SET postcode = 'S5' WHERE rowid = 62457;
UPDATE unmatched_genealogy SET postcode = 'S6 2TN' WHERE rowid = 62461;
UPDATE unmatched_genealogy SET postcode = 'S1 2HD' WHERE rowid = 62463;
UPDATE unmatched_genealogy SET postcode = 'S3 7PP' WHERE rowid = 62464;
UPDATE unmatched_genealogy SET postcode = 'S3 8RW' WHERE rowid = 62469;
UPDATE unmatched_genealogy SET postcode = 'S35' WHERE rowid = 62472;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62475;
UPDATE unmatched_genealogy SET postcode = 'S6 1WR' WHERE rowid = 62477;
UPDATE unmatched_genealogy SET postcode = 'S9 3SH' WHERE rowid = 62480;
UPDATE unmatched_genealogy SET postcode = 'S9 3FF' WHERE rowid = 62481;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 62483;
UPDATE unmatched_genealogy SET postcode = 'S11 8HF' WHERE rowid = 62488;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62491;
UPDATE unmatched_genealogy SET postcode = 'S11 8HF' WHERE rowid = 62496;
UPDATE unmatched_genealogy SET postcode = 'S3 7GF' WHERE rowid = 62498;
UPDATE unmatched_genealogy SET postcode = 'S3 7GF' WHERE rowid = 62499;
UPDATE unmatched_genealogy SET postcode = 'S10 2AF' WHERE rowid = 62503;
UPDATE unmatched_genealogy SET postcode = 'S1 4PT' WHERE rowid = 62507;
UPDATE unmatched_genealogy SET postcode = 'S2 4HJ' WHERE rowid = 62510;
UPDATE unmatched_genealogy SET postcode = 'S1 2GQ' WHERE rowid = 62513;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62522;
UPDATE unmatched_genealogy SET postcode = 'S3 7JN' WHERE rowid = 62525;
UPDATE unmatched_genealogy SET postcode = 'S12 2LG' WHERE rowid = 62528;
UPDATE unmatched_genealogy SET postcode = 'S3 7PP' WHERE rowid = 62531;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 62539;
UPDATE unmatched_genealogy SET postcode = 'S4 7PS' WHERE rowid = 62541;
UPDATE unmatched_genealogy SET postcode = 'S3 9AJ' WHERE rowid = 62547;
UPDATE unmatched_genealogy SET postcode = 'S9 3JA' WHERE rowid = 62557;
UPDATE unmatched_genealogy SET postcode = 'S1 2GA' WHERE rowid = 62561;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 62578;
UPDATE unmatched_genealogy SET postcode = 'S9 3JA' WHERE rowid = 62584;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62585;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62588;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62590;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62593;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 62598;
UPDATE unmatched_genealogy SET postcode = 'S4 7LA' WHERE rowid = 62599;
UPDATE unmatched_genealogy SET postcode = 'S9 2DD' WHERE rowid = 62600;
UPDATE unmatched_genealogy SET postcode = 'S13 9XA' WHERE rowid = 62606;
UPDATE unmatched_genealogy SET postcode = 'S1 2JB' WHERE rowid = 62611;
UPDATE unmatched_genealogy SET postcode = 'S4 7WA' WHERE rowid = 62615;
UPDATE unmatched_genealogy SET postcode = 'S12 3HX' WHERE rowid = 62619;
UPDATE unmatched_genealogy SET postcode = 'S9 1UQ' WHERE rowid = 62621;
UPDATE unmatched_genealogy SET postcode = 'S3 7JF' WHERE rowid = 62627;
UPDATE unmatched_genealogy SET postcode = 'S1 4BS' WHERE rowid = 62630;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62633;
UPDATE unmatched_genealogy SET postcode = 'S6 3BT' WHERE rowid = 62634;
UPDATE unmatched_genealogy SET postcode = 'S3 8BW' WHERE rowid = 62635;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62636;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62652;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62655;
UPDATE unmatched_genealogy SET postcode = 'S6 3DN' WHERE rowid = 62665;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 62666;
UPDATE unmatched_genealogy SET postcode = 'S11 7BJ' WHERE rowid = 62669;
UPDATE unmatched_genealogy SET postcode = 'S3 8AT' WHERE rowid = 62674;
UPDATE unmatched_genealogy SET postcode = 'S4 7EU' WHERE rowid = 62679;
UPDATE unmatched_genealogy SET postcode = 'S4 8DQ' WHERE rowid = 62680;
UPDATE unmatched_genealogy SET postcode = 'S4 7QN' WHERE rowid = 62696;
UPDATE unmatched_genealogy SET postcode = 'S1 4EA' WHERE rowid = 62697;
UPDATE unmatched_genealogy SET postcode = 'S3 8NW' WHERE rowid = 62700;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62701;
UPDATE unmatched_genealogy SET postcode = 'S13 7PG' WHERE rowid = 62702;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62703;
UPDATE unmatched_genealogy SET postcode = 'S3 7JL' WHERE rowid = 62704;
UPDATE unmatched_genealogy SET postcode = 'S3 7JN' WHERE rowid = 62705;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 62711;
UPDATE unmatched_genealogy SET postcode = 'S1 2BS' WHERE rowid = 62713;
UPDATE unmatched_genealogy SET postcode = 'S2 5AT' WHERE rowid = 62718;
UPDATE unmatched_genealogy SET postcode = 'S3 7PP' WHERE rowid = 62720;
UPDATE unmatched_genealogy SET postcode = 'S2 2QZ' WHERE rowid = 62723;
UPDATE unmatched_genealogy SET postcode = 'S1 4BS' WHERE rowid = 62728;
UPDATE unmatched_genealogy SET postcode = 'S3 8LX' WHERE rowid = 62732;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 62733;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62734;
UPDATE unmatched_genealogy SET postcode = 'S6 1WR' WHERE rowid = 62736;
UPDATE unmatched_genealogy SET postcode = 'S3 7NJ' WHERE rowid = 62747;
UPDATE unmatched_genealogy SET postcode = 'S9 2QD' WHERE rowid = 62759;
UPDATE unmatched_genealogy SET postcode = 'S6 1WR' WHERE rowid = 62761;
UPDATE unmatched_genealogy SET postcode = 'S4 7XU' WHERE rowid = 62769;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62770;
UPDATE unmatched_genealogy SET postcode = 'S1 4QB' WHERE rowid = 62778;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62781;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62784;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62800;
UPDATE unmatched_genealogy SET postcode = 'S11 8YZ' WHERE rowid = 62802;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 62805;
UPDATE unmatched_genealogy SET postcode = 'S4 7QN' WHERE rowid = 62809;
UPDATE unmatched_genealogy SET postcode = 'S3 7PA' WHERE rowid = 62815;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62824;
UPDATE unmatched_genealogy SET postcode = 'S9 4JP' WHERE rowid = 62825;
UPDATE unmatched_genealogy SET postcode = 'S9 2FZ' WHERE rowid = 62826;
UPDATE unmatched_genealogy SET postcode = 'S9 3JA' WHERE rowid = 62827;
UPDATE unmatched_genealogy SET postcode = 'S4 7LJ' WHERE rowid = 62828;
UPDATE unmatched_genealogy SET postcode = 'S6 4FA' WHERE rowid = 62831;
UPDATE unmatched_genealogy SET postcode = 'S3 8BW' WHERE rowid = 62833;
UPDATE unmatched_genealogy SET postcode = 'S8 8LB' WHERE rowid = 62848;
UPDATE unmatched_genealogy SET postcode = 'S3 7AA' WHERE rowid = 62851;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62852;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62853;
UPDATE unmatched_genealogy SET postcode = 'S3 7BA' WHERE rowid = 62855;
UPDATE unmatched_genealogy SET postcode = 'S1 2GJ' WHERE rowid = 62856;
UPDATE unmatched_genealogy SET postcode = 'S3 7JL' WHERE rowid = 62857;
UPDATE unmatched_genealogy SET postcode = 'S3 7JN' WHERE rowid = 62858;
UPDATE unmatched_genealogy SET postcode = 'S3 7AD' WHERE rowid = 62859;
UPDATE unmatched_genealogy SET postcode = 'S3 7AD' WHERE rowid = 62860;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 62863;
UPDATE unmatched_genealogy SET postcode = 'S3 7NQ' WHERE rowid = 62865;
UPDATE unmatched_genealogy SET postcode = 'S3 7NW' WHERE rowid = 62866;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 62867;
UPDATE unmatched_genealogy SET postcode = 'S3 7PP' WHERE rowid = 62870;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62873;
UPDATE unmatched_genealogy SET postcode = 'S1 4QB' WHERE rowid = 62874;
UPDATE unmatched_genealogy SET postcode = 'S1 2GA' WHERE rowid = 62877;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 62891;
UPDATE unmatched_genealogy SET postcode = 'S1 4EA' WHERE rowid = 62892;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 62896;
UPDATE unmatched_genealogy SET postcode = 'S3 8RP' WHERE rowid = 62898;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 62901;
UPDATE unmatched_genealogy SET postcode = 'S3 7BA' WHERE rowid = 62902;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 62905;
UPDATE unmatched_genealogy SET postcode = 'S2 4AF' WHERE rowid = 62906;
UPDATE unmatched_genealogy SET postcode = 'S1 2JB' WHERE rowid = 62909;
UPDATE unmatched_genealogy SET postcode = 'S1 2GA' WHERE rowid = 62913;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 62918;
UPDATE unmatched_genealogy SET postcode = 'S4 7PS' WHERE rowid = 62923;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 62925;
UPDATE unmatched_genealogy SET postcode = 'S1 4RF' WHERE rowid = 62950;
UPDATE unmatched_genealogy SET postcode = 'S6 3DN' WHERE rowid = 62951;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62952;
UPDATE unmatched_genealogy SET postcode = 'S3 7PL' WHERE rowid = 62953;
UPDATE unmatched_genealogy SET postcode = 'S6 2XJ' WHERE rowid = 62955;
UPDATE unmatched_genealogy SET postcode = 'S6 2XJ' WHERE rowid = 62956;
UPDATE unmatched_genealogy SET postcode = 'S3 8RW' WHERE rowid = 62965;
UPDATE unmatched_genealogy SET postcode = 'S1 4JU' WHERE rowid = 62971;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62974;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 62975;
UPDATE unmatched_genealogy SET postcode = 'S1 2PF' WHERE rowid = 62989;
UPDATE unmatched_genealogy SET postcode = 'S2 4HJ' WHERE rowid = 62990;
UPDATE unmatched_genealogy SET postcode = 'S3 7JN' WHERE rowid = 63003;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 63006;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63011;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 63014;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 63020;
UPDATE unmatched_genealogy SET postcode = 'S3 7PP' WHERE rowid = 63026;
UPDATE unmatched_genealogy SET postcode = 'S3 7AR' WHERE rowid = 63043;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63065;
UPDATE unmatched_genealogy SET postcode = 'S1 2JB' WHERE rowid = 63067;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63068;
UPDATE unmatched_genealogy SET postcode = 'S1 2GJ' WHERE rowid = 63069;
UPDATE unmatched_genealogy SET postcode = 'S9 2FZ' WHERE rowid = 63081;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 63082;
UPDATE unmatched_genealogy SET postcode = 'S3 7NJ' WHERE rowid = 63083;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63087;
UPDATE unmatched_genealogy SET postcode = 'S11 7EU' WHERE rowid = 63088;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 63093;
UPDATE unmatched_genealogy SET postcode = 'S1 4BS' WHERE rowid = 63099;
UPDATE unmatched_genealogy SET postcode = 'S1 2HD' WHERE rowid = 63109;
UPDATE unmatched_genealogy SET postcode = 'S3 7EF' WHERE rowid = 63113;
UPDATE unmatched_genealogy SET postcode = 'S4 8AD' WHERE rowid = 63114;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63115;
UPDATE unmatched_genealogy SET postcode = 'S3 7JL' WHERE rowid = 63116;
UPDATE unmatched_genealogy SET postcode = 'S3 7JL' WHERE rowid = 63118;
UPDATE unmatched_genealogy SET postcode = 'S3 7JF' WHERE rowid = 63120;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63123;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63124;
UPDATE unmatched_genealogy SET postcode = 'S3 8BW' WHERE rowid = 63127;
UPDATE unmatched_genealogy SET postcode = 'S3 8BW' WHERE rowid = 63128;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 63129;
UPDATE unmatched_genealogy SET postcode = 'S1 2BS' WHERE rowid = 63135;
UPDATE unmatched_genealogy SET postcode = 'S2 4BA' WHERE rowid = 63144;
UPDATE unmatched_genealogy SET postcode = 'S1 2AT' WHERE rowid = 63148;
UPDATE unmatched_genealogy SET postcode = 'S9 5AB' WHERE rowid = 63152;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63161;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 63165;
UPDATE unmatched_genealogy SET postcode = 'S3 7PH' WHERE rowid = 63174;
UPDATE unmatched_genealogy SET postcode = 'S17' WHERE rowid = 63187;
UPDATE unmatched_genealogy SET postcode = 'S1 4EF' WHERE rowid = 63188;
UPDATE unmatched_genealogy SET postcode = 'S7 1RA' WHERE rowid = 63189;
UPDATE unmatched_genealogy SET postcode = 'S1 4RF' WHERE rowid = 63192;
UPDATE unmatched_genealogy SET postcode = 'S1 4RF' WHERE rowid = 63193;
UPDATE unmatched_genealogy SET postcode = 'S9 4JP' WHERE rowid = 63194;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63198;
UPDATE unmatched_genealogy SET postcode = 'S1 4EA' WHERE rowid = 63199;
UPDATE unmatched_genealogy SET postcode = 'S3 8NS' WHERE rowid = 63210;
UPDATE unmatched_genealogy SET postcode = 'S3 8RP' WHERE rowid = 63211;
UPDATE unmatched_genealogy SET postcode = 'S3 7AA' WHERE rowid = 63215;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63218;
UPDATE unmatched_genealogy SET postcode = 'S10 5NT' WHERE rowid = 63220;
UPDATE unmatched_genealogy SET postcode = 'S3 7AR' WHERE rowid = 63227;
UPDATE unmatched_genealogy SET postcode = 'S3 7BA' WHERE rowid = 63229;
UPDATE unmatched_genealogy SET postcode = 'S3 7JL' WHERE rowid = 63230;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63231;
UPDATE unmatched_genealogy SET postcode = 'S3 7ES' WHERE rowid = 63233;
UPDATE unmatched_genealogy SET postcode = 'S1 2JB' WHERE rowid = 63234;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 63236;
UPDATE unmatched_genealogy SET postcode = 'S2 5QA' WHERE rowid = 63237;
UPDATE unmatched_genealogy SET postcode = 'S4 7ZE' WHERE rowid = 63240;
UPDATE unmatched_genealogy SET postcode = 'S3 7GF' WHERE rowid = 63241;
UPDATE unmatched_genealogy SET postcode = 'S6 3BT' WHERE rowid = 63242;
UPDATE unmatched_genealogy SET postcode = 'S3 7NQ' WHERE rowid = 63246;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 63248;
UPDATE unmatched_genealogy SET postcode = 'S1 2BS' WHERE rowid = 63251;
UPDATE unmatched_genealogy SET postcode = 'S1 2NG' WHERE rowid = 63256;
UPDATE unmatched_genealogy SET postcode = 'S1 4RG' WHERE rowid = 63257;
UPDATE unmatched_genealogy SET postcode = 'S1 2NG' WHERE rowid = 63258;
UPDATE unmatched_genealogy SET postcode = 'S1 4QB' WHERE rowid = 63259;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 63265;
UPDATE unmatched_genealogy SET postcode = 'S2 5QA' WHERE rowid = 63271;
UPDATE unmatched_genealogy SET postcode = 'S1 4DT' WHERE rowid = 63274;
UPDATE unmatched_genealogy SET postcode = 'S3 7PH' WHERE rowid = 63276;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 63284;
UPDATE unmatched_genealogy SET postcode = 'S1 2GJ' WHERE rowid = 63287;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63291;
UPDATE unmatched_genealogy SET postcode = 'S9 1UQ' WHERE rowid = 63303;
UPDATE unmatched_genealogy SET postcode = 'S3 7NJ' WHERE rowid = 63320;
UPDATE unmatched_genealogy SET postcode = 'S3 7EU' WHERE rowid = 63341;
UPDATE unmatched_genealogy SET postcode = 'S1 4QB' WHERE rowid = 63344;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63346;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63347;
UPDATE unmatched_genealogy SET postcode = 'S6 2TN' WHERE rowid = 63348;
UPDATE unmatched_genealogy SET postcode = 'S6 2TQ' WHERE rowid = 63350;
UPDATE unmatched_genealogy SET postcode = 'S9 5AB' WHERE rowid = 63357;
UPDATE unmatched_genealogy SET postcode = 'S9 5AB' WHERE rowid = 63358;
UPDATE unmatched_genealogy SET postcode = 'S1 2BA' WHERE rowid = 63359;
UPDATE unmatched_genealogy SET postcode = 'S10 3PA' WHERE rowid = 63362;
UPDATE unmatched_genealogy SET postcode = 'S9 3FF' WHERE rowid = 63372;
UPDATE unmatched_genealogy SET postcode = 'S4 7AB' WHERE rowid = 63374;
UPDATE unmatched_genealogy SET postcode = 'S3 8LT' WHERE rowid = 63378;
UPDATE unmatched_genealogy SET postcode = 'S11 8HF' WHERE rowid = 63383;
UPDATE unmatched_genealogy SET postcode = 'S3 7EU' WHERE rowid = 63385;
UPDATE unmatched_genealogy SET postcode = 'S10 2FW' WHERE rowid = 63386;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63387;
UPDATE unmatched_genealogy SET postcode = 'S10 2AF' WHERE rowid = 63389;
UPDATE unmatched_genealogy SET postcode = 'S10 5DF' WHERE rowid = 63390;
UPDATE unmatched_genealogy SET postcode = 'S1 2PF' WHERE rowid = 63392;
UPDATE unmatched_genealogy SET postcode = 'S2 4HJ' WHERE rowid = 63395;
UPDATE unmatched_genealogy SET postcode = 'S12 2LG' WHERE rowid = 63410;
UPDATE unmatched_genealogy SET postcode = 'S13 9XA' WHERE rowid = 63414;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 63415;
UPDATE unmatched_genealogy SET postcode = 'S3 9AD' WHERE rowid = 63425;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 63432;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 63435;
UPDATE unmatched_genealogy SET postcode = 'S6' WHERE rowid = 63440;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63448;
UPDATE unmatched_genealogy SET postcode = 'S3 8LF' WHERE rowid = 63454;
UPDATE unmatched_genealogy SET postcode = 'S1 2GA' WHERE rowid = 63469;
UPDATE unmatched_genealogy SET postcode = 'S4 8DQ' WHERE rowid = 63473;
UPDATE unmatched_genealogy SET postcode = 'S1 4DT' WHERE rowid = 63474;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 63481;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 63491;
UPDATE unmatched_genealogy SET postcode = 'S1 2GQ' WHERE rowid = 63498;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63500;
UPDATE unmatched_genealogy SET postcode = 'S9 4QB' WHERE rowid = 63505;
UPDATE unmatched_genealogy SET postcode = 'S1 4QB' WHERE rowid = 63509;
UPDATE unmatched_genealogy SET postcode = 'S2 2TH' WHERE rowid = 63513;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63514;
UPDATE unmatched_genealogy SET postcode = 'S13 9XA' WHERE rowid = 63523;
UPDATE unmatched_genealogy SET postcode = 'S13 9XA' WHERE rowid = 63524;
UPDATE unmatched_genealogy SET postcode = 'S9 2FZ' WHERE rowid = 63525;
UPDATE unmatched_genealogy SET postcode = 'S4 7LJ' WHERE rowid = 63542;
UPDATE unmatched_genealogy SET postcode = 'S3 7SU' WHERE rowid = 63543;
UPDATE unmatched_genealogy SET postcode = 'S10 2FJ' WHERE rowid = 63546;
UPDATE unmatched_genealogy SET postcode = 'S2 5QA' WHERE rowid = 63547;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63548;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63557;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63558;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 63559;
UPDATE unmatched_genealogy SET postcode = 'S1 2GH' WHERE rowid = 63562;
UPDATE unmatched_genealogy SET postcode = 'S3 9PB' WHERE rowid = 63564;
UPDATE unmatched_genealogy SET postcode = 'S13 7PG' WHERE rowid = 63565;
UPDATE unmatched_genealogy SET postcode = 'S4 7EL' WHERE rowid = 63578;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63589;
UPDATE unmatched_genealogy SET postcode = 'S6 3AA' WHERE rowid = 63595;
UPDATE unmatched_genealogy SET postcode = 'S3 8DR' WHERE rowid = 63596;
UPDATE unmatched_genealogy SET postcode = 'S1 2GJ' WHERE rowid = 63597;
UPDATE unmatched_genealogy SET postcode = 'S1 2GY' WHERE rowid = 63599;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63605;
UPDATE unmatched_genealogy SET postcode = 'S1 4BA' WHERE rowid = 63606;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63608;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63609;
UPDATE unmatched_genealogy SET postcode = 'S6 3BT' WHERE rowid = 63611;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63618;
UPDATE unmatched_genealogy SET postcode = 'S1 4QU' WHERE rowid = 63620;
UPDATE unmatched_genealogy SET postcode = 'S3 7PP' WHERE rowid = 63621;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 63626;
UPDATE unmatched_genealogy SET postcode = 'S17' WHERE rowid = 63627;
UPDATE unmatched_genealogy SET postcode = 'S1 2GH' WHERE rowid = 63634;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63636;
UPDATE unmatched_genealogy SET postcode = 'S12' WHERE rowid = 63638;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 63641;
UPDATE unmatched_genealogy SET postcode = 'S6 3AW' WHERE rowid = 63642;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63644;
UPDATE unmatched_genealogy SET postcode = 'S13' WHERE rowid = 63646;
UPDATE unmatched_genealogy SET postcode = 'S3 7JL' WHERE rowid = 63647;
UPDATE unmatched_genealogy SET postcode = 'S4 8AD' WHERE rowid = 63651;
UPDATE unmatched_genealogy SET postcode = 'S3 9LN' WHERE rowid = 63653;
UPDATE unmatched_genealogy SET postcode = 'S1 2GJ' WHERE rowid = 63658;
UPDATE unmatched_genealogy SET postcode = 'S1 4PA' WHERE rowid = 63659;
UPDATE unmatched_genealogy SET postcode = 'S1 4BS' WHERE rowid = 63660;
UPDATE unmatched_genealogy SET postcode = 'S3 7BP' WHERE rowid = 63663;
UPDATE unmatched_genealogy SET postcode = 'S1 2GJ' WHERE rowid = 63683;
UPDATE unmatched_genealogy SET postcode = 'S3 7ES' WHERE rowid = 63686;
UPDATE unmatched_genealogy SET postcode = 'S6 3DN' WHERE rowid = 63705;
UPDATE unmatched_genealogy SET postcode = 'S6 3DN' WHERE rowid = 63706;
UPDATE unmatched_genealogy SET postcode = 'S4 7XU' WHERE rowid = 63710;
UPDATE unmatched_genealogy SET postcode = 'S10 2PQ' WHERE rowid = 63713;