/// Sheffield Rules Historical Clubs (1857-1875)
///
/// Contains all known Sheffield-area football clubs that played Sheffield Rules,
/// with their founding years and ground information.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SheffieldClub {
    pub id: String,
    pub name: String,
    pub founded_year: u32,
    pub ground: String,
    pub origin: String, // "Church", "Works", "Hotel", "School", "Park", "Other"
    pub city: Option<String>, // Area name (e.g., "Loxley", "Heeley", "Dore")
    pub region: Option<String>, // Sheffield postcode (e.g., "S6", "S2", "S17")
}

/// Get all Sheffield clubs with optional year filtering
/// If year is provided, only returns clubs founded by that year
pub fn get_sheffield_clubs(filter_by_year: Option<u32>) -> Vec<SheffieldClub> {
    let all_clubs = all_clubs_data();

    match filter_by_year {
        Some(year) => all_clubs.into_iter()
            .filter(|club| club.founded_year <= year)
            .collect(),
        None => all_clubs,
    }
}

/// Get clubs available at the start of a game
/// - Historical Timeline: only clubs formed by 1857
/// - Ahistorical & Historical From Year: clubs formed by that year
pub fn get_clubs_for_game_mode(start_year: u32) -> Vec<SheffieldClub> {
    get_sheffield_clubs(Some(start_year))
}

fn all_clubs_data() -> Vec<SheffieldClub> {
    vec![
        // 1857-1858
        SheffieldClub {
            id: "sheffield-fc".to_string(),
            name: "Sheffield FC".to_string(),
            founded_year: 1857,
            ground: "East Bank".to_string(),
            origin: "played at East Bank".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        // 1860
        SheffieldClub {
            id: "hallam-fc".to_string(),
            name: "Hallam FC".to_string(),
            founded_year: 1860,
            ground: "Sandygate".to_string(),
            origin: "play at Sandygate".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        // 1861
        SheffieldClub {
            id: "norfolk-fc".to_string(),
            name: "Norfolk FC".to_string(),
            founded_year: 1861,
            ground: "Norfolk Park".to_string(),
            origin: "played at Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "cemetery-road-church-fc".to_string(),
            name: "Cemetery Road Church FC".to_string(),
            founded_year: 1861,
            ground: "Hunters Bar".to_string(),
            origin: "Oldest church club, played at Hunters Bar".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "york-fc".to_string(),
            name: "York FC".to_string(),
            founded_year: 1861,
            ground: "Endcliffe Cricket Ground".to_string(),
            origin: "From York Hotel, Broomhill, played at Endcliﬀe Cricket Ground, N Creswick was President".to_string(),
            city: Some("Broomhill".to_string()),
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "norton-fc".to_string(),
            name: "Norton FC".to_string(),
            founded_year: 1861,
            ground: "Oaks Park".to_string(),
            origin: "played at Oaks Park, Norton".to_string(),
            city: Some("Norton".to_string()),
            region: Some("S8".to_string()),
        },
        SheffieldClub {
            id: "pitsmoor-fc".to_string(),
            name: "Pitsmoor FC".to_string(),
            founded_year: 1861,
            ground: "Pitsmoor CC".to_string(),
            origin: "played at Pitsmoor CC, now SUFC Academy".to_string(),
            city: Some("Pitsmoor".to_string()),
            region: Some("S4".to_string()),
        },
        // 1862
        SheffieldClub {
            id: "fir-vale-fc".to_string(),
            name: "Fir Vale FC".to_string(),
            founded_year: 1862,
            ground: "Pitsmoor CC".to_string(),
            origin: "played at Pitsmoor CC, now SUFC Academy".to_string(),
            city: Some("Pitsmoor".to_string()),
            region: Some("S4".to_string()),
        },
        SheffieldClub {
            id: "heeley-christ-church-fc".to_string(),
            name: "Heeley Christ Church FC".to_string(),
            founded_year: 1862,
            ground: "Meersbrook Park".to_string(),
            origin: "played at Meersbrook Park".to_string(),
            city: Some("Meersbrook".to_string()),
            region: Some("S8".to_string()),
        },
        SheffieldClub {
            id: "mackenzie-fc".to_string(),
            name: "Mackenzie FC".to_string(),
            founded_year: 1862,
            ground: "Myrtle Road, Heeley".to_string(),
            origin: "played at Myrtle Road, Heeley".to_string(),
            city: Some("Heeley".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "milton-fc".to_string(),
            name: "Milton FC".to_string(),
            founded_year: 1862,
            ground: "Cremorne Gardens, London Road".to_string(),
            origin: "played at Cremorne Gardens, London Road".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "howard-hill-steel-bank-fc".to_string(),
            name: "Howard Hill Steel Bank FC".to_string(),
            founded_year: 1862,
            ground: "Howard Hotel, Howard Road".to_string(),
            origin: "Met in Howard Hotel, Howard Road".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "ranmoor-fc".to_string(),
            name: "Ranmoor FC".to_string(),
            founded_year: 1862,
            ground: "Ranmoor".to_string(),
            origin: "played in Ranmoor".to_string(),
            city: Some("Ranmoor".to_string()),
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "st-george-fc".to_string(),
            name: "St George FC".to_string(),
            founded_year: 1862,
            ground: "Broad Lane".to_string(),
            origin: "From St George's Church, Broad Lane.".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "st-stephen-fc".to_string(),
            name: "St Stephen FC".to_string(),
            founded_year: 1862,
            ground: "Crookes".to_string(),
            origin: "From St Stephen's Church Fawcett Road Netherthorpe. Played at Crookes.".to_string(),
            city: Some("Netherthorpe".to_string()),
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "united-norfolk-fc".to_string(),
            name: "United Norfolk FC".to_string(),
            founded_year: 1862,
            ground: "Unknown".to_string(),
            origin: "Origins uncertain".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        // 1863
        SheffieldClub {
            id: "crabtree-fc".to_string(),
            name: "Crabtree FC".to_string(),
            founded_year: 1863,
            ground: "Fir Vale area".to_string(),
            origin: "Likely from Fir Vale area".to_string(),
            city: Some("Fir Vale".to_string()),
            region: Some("S4".to_string()),
        },
        SheffieldClub {
            id: "broomhall-fc".to_string(),
            name: "Broomhall FC".to_string(),
            founded_year: 1863,
            ground: "Ecclesall Road".to_string(),
            origin: "played at Ecclesall Road".to_string(),
            city: Some("Ecclesall".to_string()),
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "tudor-fc".to_string(),
            name: "Tudor FC".to_string(),
            founded_year: 1863,
            ground: "Unknown".to_string(),
            origin: "Other".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "w-h-hutchinson-fc".to_string(),
            name: "W & H Hutchinson's FC".to_string(),
            founded_year: 1863,
            ground: "Unknown".to_string(),
            origin: "Works".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "hemsworth-fc".to_string(),
            name: "Hemsworth FC".to_string(),
            founded_year: 1863,
            ground: "Unknown".to_string(),
            origin: "Other".to_string(),
            city: None,
            region: Some("S5".to_string()),
        },
        // 1865
        SheffieldClub {
            id: "united-mechanics".to_string(),
            name: "United Mechanics".to_string(),
            founded_year: 1865,
            ground: "Norfolk Park".to_string(),
            origin: "played at Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        // 1866
        SheffieldClub {
            id: "garrick-fc".to_string(),
            name: "Garrick FC".to_string(),
            founded_year: 1866,
            ground: "East Bank".to_string(),
            origin: "played at East Bank".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "wellington-fc".to_string(),
            name: "Wellington FC".to_string(),
            founded_year: 1866,
            ground: "Hounsfield Park".to_string(),
            origin: "played at Hounsﬁeld Park near Bramall Lane".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "loxley-fc".to_string(),
            name: "Loxley FC".to_string(),
            founded_year: 1866,
            ground: "The Rodney Inn, Loxley".to_string(),
            origin: "Met at The Rodney Inn, Loxley".to_string(),
            city: Some("Loxley".to_string()),
            region: Some("S6".to_string()),
        },
        // 1867
        SheffieldClub {
            id: "wednesday-fc".to_string(),
            name: "Wednesday FC".to_string(),
            founded_year: 1867,
            ground: "Highfields, now Hillsborough".to_string(),
            origin: "played at Highﬁelds, now Hillsborough".to_string(),
            city: Some("Hillsborough".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "exchange-fc".to_string(),
            name: "Exchange FC".to_string(),
            founded_year: 1867,
            ground: "Hallam's Farm, now Hyde Park Flats".to_string(),
            origin: "played at Hallam's Farm, now Hyde Park Flats".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "dore-fc".to_string(),
            name: "Dore FC".to_string(),
            founded_year: 1867,
            ground: "The Devonshire Arms, Dore".to_string(),
            origin: "Met at The Devonshire Arms, Dore".to_string(),
            city: Some("Dore".to_string()),
            region: Some("S17".to_string()),
        },
        SheffieldClub {
            id: "tapton-fc".to_string(),
            name: "Tapton FC".to_string(),
            founded_year: 1867,
            ground: "Tapton Hall".to_string(),
            origin: "Based at Tapton Hall".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        // 1868
        SheffieldClub {
            id: "dronfield-fc".to_string(),
            name: "Dronfield FC".to_string(),
            founded_year: 1868,
            ground: "Bagley's Field, Dronfield".to_string(),
            origin: "played at Bagley's Field, Dronfield".to_string(),
            city: None,
            region: Some("S18".to_string()),
        },
        SheffieldClub {
            id: "brincliffe-fc".to_string(),
            name: "Brincliffe FC".to_string(),
            founded_year: 1868,
            ground: "Cherry Tree Farm".to_string(),
            origin: "played at Cherry Tree Farm, near Union pub".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "hanover-united-fc".to_string(),
            name: "Hanover United FC".to_string(),
            founded_year: 1868,
            ground: "Crookes".to_string(),
            origin: "played at Crookes".to_string(),
            city: Some("Crookes".to_string()),
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "stannington-fc".to_string(),
            name: "Stannington FC".to_string(),
            founded_year: 1868,
            ground: "Unknown".to_string(),
            origin: "unknown ground loca_on".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "redhill-fc".to_string(),
            name: "Redhill FC".to_string(),
            founded_year: 1868,
            ground: "Winter Street, near Weston Park".to_string(),
            origin: "played at Winter Street, near Weston Park".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        // 1869
        SheffieldClub {
            id: "parkwood-springs-fc".to_string(),
            name: "Parkwood Springs FC".to_string(),
            founded_year: 1869,
            ground: "Parkwood Springs Recreation Ground".to_string(),
            origin: "played at Parkwood Springs Recrea_on Ground".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "oxford-fc".to_string(),
            name: "Oxford FC".to_string(),
            founded_year: 1869,
            ground: "Ecclesall Road".to_string(),
            origin: "played at Ecclesall Road".to_string(),
            city: Some("Ecclesall".to_string()),
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "totley-fc".to_string(),
            name: "Totley FC".to_string(),
            founded_year: 1869,
            ground: "Cross Scythes Inn, Totley".to_string(),
            origin: "played at ﬁeld next to Cross Scythes Inn, Totley".to_string(),
            city: Some("Totley".to_string()),
            region: Some("S17".to_string()),
        },
        SheffieldClub {
            id: "sheffield-norfolk-fc".to_string(),
            name: "Sheffield Norfolk FC".to_string(),
            founded_year: 1869,
            ground: "Unknown".to_string(),
            origin: "Other".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "st-vincent-fc".to_string(),
            name: "St Vincent's".to_string(),
            founded_year: 1869,
            ground: "Queens Ground".to_string(),
            origin: "from Solly Street – played at Queens Ground".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "st-james-church-fc".to_string(),
            name: "St James Church FC".to_string(),
            founded_year: 1869,
            ground: "Norton Lees Lane".to_string(),
            origin: "played at Norton Lees Lane".to_string(),
            city: Some("Norton Lees".to_string()),
            region: Some("S8".to_string()),
        },
        // 1870
        SheffieldClub {
            id: "lockwood-brothers-fc".to_string(),
            name: "Lockwood Brothers FC".to_string(),
            founded_year: 1870,
            ground: "Hunters Bar".to_string(),
            origin: "played at Hunters Bar, oldest works club".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "talbot-fc".to_string(),
            name: "Talbot FC".to_string(),
            founded_year: 1870,
            ground: "Norfolk Road".to_string(),
            origin: "played at Norfolk Road".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "sheffield-united-gymnastic-club".to_string(),
            name: "Sheffield United Gymnastic Club".to_string(),
            founded_year: 1870,
            ground: "Unknown".to_string(),
            origin: "Other".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "ecclesall-college-fc".to_string(),
            name: "Ecclesall College FC".to_string(),
            founded_year: 1870,
            ground: "Unknown".to_string(),
            origin: "School".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "sheffield-grammar-school-fc".to_string(),
            name: "Sheffield Grammar School FC".to_string(),
            founded_year: 1870,
            ground: "Unknown".to_string(),
            origin: "School".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "surrey-catholic-club".to_string(),
            name: "Surrey Catholic Club".to_string(),
            founded_year: 1870,
            ground: "The Farm, now Sheffield College".to_string(),
            origin: "played at The Farm, now Sheﬃeld College".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "attercliffe-christ-church".to_string(),
            name: "Attercliffe (Christ Church)".to_string(),
            founded_year: 1870,
            ground: "The Old Forge Ground, Shirland Lane".to_string(),
            origin: "played at The Old Forge Ground, Shirland Lane".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "walkey-new-connexion-fc".to_string(),
            name: "Walkey New Connexion FC".to_string(),
            founded_year: 1870,
            ground: "Queens Ground, Hillsborough".to_string(),
            origin: "played at Queens Ground, Hillsborough".to_string(),
            city: Some("Hillsborough".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "crookes-fc".to_string(),
            name: "Crookes FC".to_string(),
            founded_year: 1870,
            ground: "Lydgate Lane".to_string(),
            origin: "played at Lydgate Lane".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "bankers-thursday".to_string(),
            name: "Bankers / Thursday".to_string(),
            founded_year: 1870,
            ground: "Hunters Bar".to_string(),
            origin: "played at Hunters Bar".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "alliance-fc".to_string(),
            name: "Alliance FC".to_string(),
            founded_year: 1870,
            ground: "Norfolk Park".to_string(),
            origin: "played at Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "perseverance-fc".to_string(),
            name: "Perseverance FC".to_string(),
            founded_year: 1870,
            ground: "Norfolk Park".to_string(),
            origin: "played at Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "gleadless-fc".to_string(),
            name: "Gleadless FC".to_string(),
            founded_year: 1870,
            ground: "Charnock Hall, Gleadless".to_string(),
            origin: "played at Charnock Hall, Gleadless".to_string(),
            city: Some("Gleadless".to_string()),
            region: Some("S12".to_string()),
        },
        SheffieldClub {
            id: "engineers-fc".to_string(),
            name: "Engineers FC".to_string(),
            founded_year: 1870,
            ground: "Endcliffe Crescent".to_string(),
            origin: "Played at Endcliﬀe Crescent".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        // 1871
        SheffieldClub {
            id: "attercliffe-zion-fc".to_string(),
            name: "Attercliffe Zion FC".to_string(),
            founded_year: 1871,
            ground: "Unknown".to_string(),
            origin: "from Zion Church, Attercliffe".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "grimesthorpe-fc".to_string(),
            name: "Grimesthorpe FC".to_string(),
            founded_year: 1871,
            ground: "Victoria Hotel, Grimesthorpe".to_string(),
            origin: "Met at Victoria Hotel, Grimesthorpe".to_string(),
            city: Some("Grimesthorpe".to_string()),
            region: Some("S4".to_string()),
        },
        SheffieldClub {
            id: "exchange-brewery-fc".to_string(),
            name: "Exchange Brewery FC".to_string(),
            founded_year: 1871,
            ground: "Fox Street, Pye Bank".to_string(),
            origin: "played at Fox Street, Pye Bank".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "all-saints-night-school-fc".to_string(),
            name: "All Saints Night School FC".to_string(),
            founded_year: 1871,
            ground: "Hall Carr Lane, now Carwood Road".to_string(),
            origin: "Hall Carr Lane, now Carwood Road".to_string(),
            city: None,
            region: Some("S4".to_string()),
        },
        SheffieldClub {
            id: "millhouses-fc".to_string(),
            name: "Millhouses FC".to_string(),
            founded_year: 1871,
            ground: "The Old Corn Mill".to_string(),
            origin: "possibly played at The Old Corn Mill".to_string(),
            city: None,
            region: Some("S7".to_string()),
        },
        // 1872
        SheffieldClub {
            id: "albion-fc".to_string(),
            name: "Albion FC".to_string(),
            founded_year: 1872,
            ground: "Ecclesall Road".to_string(),
            origin: "played at Ecclesall Road".to_string(),
            city: Some("Ecclesall".to_string()),
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "pye-bank-fc".to_string(),
            name: "Pye Bank FC".to_string(),
            founded_year: 1872,
            ground: "Fox Street, Pye Bank".to_string(),
            origin: "played at Fox Street, Pye Bank".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "brightside-fc".to_string(),
            name: "Brightside FC".to_string(),
            founded_year: 1872,
            ground: "Blackburn Meadows".to_string(),
            origin: "played at Blackburn Meadows, Blackburn".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "norfolk-works-fc".to_string(),
            name: "Norfolk Works FC".to_string(),
            founded_year: 1872,
            ground: "Newhall Athletic Ground".to_string(),
            origin: "Played at Newhall Athle_c Ground".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "eldon-st-jude-fc".to_string(),
            name: "Eldon St Jude's FC".to_string(),
            founded_year: 1872,
            ground: "Brocco Bank".to_string(),
            origin: "played at Brocco Bank".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "garden-street-fc".to_string(),
            name: "Garden Street FC".to_string(),
            founded_year: 1872,
            ground: "Hollins Crog".to_string(),
            origin: "From Garden Street, Hollins Crog".to_string(),
            city: None,
            region: Some("S4".to_string()),
        },
        // 1873 - Major expansion
        SheffieldClub {
            id: "sharrow-rangers-fc".to_string(),
            name: "Sharrow Rangers FC".to_string(),
            founded_year: 1873,
            ground: "Crescent Road, Sharrow".to_string(),
            origin: "played at Crescent Road, Sharrow".to_string(),
            city: Some("Sharrow".to_string()),
            region: Some("S7".to_string()),
        },
        SheffieldClub {
            id: "endcliffe-fc".to_string(),
            name: "Endcliffe FC".to_string(),
            founded_year: 1873,
            ground: "Ecclesall Road".to_string(),
            origin: "played at Ecclesall Road".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "owlerton-fc".to_string(),
            name: "Owlerton FC".to_string(),
            founded_year: 1873,
            ground: "Rawson's Meadow Ground, Owlerton".to_string(),
            origin: "played at Rawson's Meadow Ground, Owlerton".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "ecclesfield-fc".to_string(),
            name: "Ecclesfield FC".to_string(),
            founded_year: 1873,
            ground: "Fairham's Crog".to_string(),
            origin: "played at Fairham's Crog".to_string(),
            city: None,
            region: Some("S35".to_string()),
        },
        SheffieldClub {
            id: "philadelphia-fc".to_string(),
            name: "Philadelphia FC".to_string(),
            founded_year: 1873,
            ground: "Queens Ground, Hillsborough".to_string(),
            origin: "played at Queens Ground Hillsborough".to_string(),
            city: Some("Hillsborough".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "artillery-hallamshire-fc".to_string(),
            name: "Artillery & Hallamshire FC".to_string(),
            founded_year: 1873,
            ground: "Endcliffe Hall".to_string(),
            origin: "Based at Endcliﬀe Hall (later just Artillery)".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "intake-fc".to_string(),
            name: "Intake FC".to_string(),
            founded_year: 1873,
            ground: "Intake".to_string(),
            origin: "From Intake".to_string(),
            city: Some("Intake".to_string()),
            region: Some("S12".to_string()),
        },
        SheffieldClub {
            id: "cherrytree-fc".to_string(),
            name: "Cherrytree FC".to_string(),
            founded_year: 1873,
            ground: "Cherrytree Orphanage".to_string(),
            origin: "Possibly from Cherrytree Orphanage".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "victoria-burngreave-fc".to_string(),
            name: "Victoria (Burngreave) FC".to_string(),
            founded_year: 1873,
            ground: "Hall Carr Lane".to_string(),
            origin: "played at Hall Carr Lane, east end".to_string(),
            city: None,
            region: Some("S4".to_string()),
        },
        SheffieldClub {
            id: "west-end-fc".to_string(),
            name: "West End FC".to_string(),
            founded_year: 1873,
            ground: "Hunters Bar".to_string(),
            origin: "played at Hunters Bar, from West End Hotel".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "bury-co-fc".to_string(),
            name: "Bury's & Co FC".to_string(),
            founded_year: 1873,
            ground: "Regents Works".to_string(),
            origin: "From Regents Works, now Wicks".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "beadshaw-baltic-fc".to_string(),
            name: "Beadshaw's (Baltic) FC".to_string(),
            founded_year: 1873,
            ground: "Baltic Works, Attercliffe".to_string(),
            origin: "From Baltic Works, Attercliffe".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "oughtibridge-fc".to_string(),
            name: "Oughtibridge FC".to_string(),
            founded_year: 1873,
            ground: "Oughtibridge".to_string(),
            origin: "From Oughtibridge".to_string(),
            city: Some("Oughtibridge".to_string()),
            region: Some("S35".to_string()),
        },
        SheffieldClub {
            id: "weston-fc".to_string(),
            name: "Weston FC".to_string(),
            founded_year: 1873,
            ground: "Weston Hall".to_string(),
            origin: "Possibly played at Weston Hall".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "wardsend-steel-works-fc".to_string(),
            name: "Wardsend Steel Works FC".to_string(),
            founded_year: 1873,
            ground: "Herries Road".to_string(),
            origin: "From Wardsend Steel Works, Herries Road".to_string(),
            city: None,
            region: Some("S5".to_string()),
        },
        SheffieldClub {
            id: "owlerton-reform-fc".to_string(),
            name: "Owlerton Reform FC".to_string(),
            founded_year: 1873,
            ground: "Borough Road, Owlerton".to_string(),
            origin: "From Wesleyan Reform Church on Borough Road, Owlerton".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "roebuck-fc".to_string(),
            name: "Roebuck FC".to_string(),
            founded_year: 1873,
            ground: "East Bank".to_string(),
            origin: "Roebuck pub, played at East Bank".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "tennant-brothers-fc".to_string(),
            name: "Tennant Brothers & Co FC".to_string(),
            founded_year: 1873,
            ground: "Exchange Brewery".to_string(),
            origin: "club from Exchange Brewery".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "crosspool-rangers-fc".to_string(),
            name: "Crosspool Rangers FC".to_string(),
            founded_year: 1873,
            ground: "Crosspool".to_string(),
            origin: "From Crosspool".to_string(),
            city: Some("Crosspool".to_string()),
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "clifford-fc".to_string(),
            name: "Clifford FC".to_string(),
            founded_year: 1873,
            ground: "Psalter Lane".to_string(),
            origin: "From Clifford House, Psalter Lane".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "grange-fc".to_string(),
            name: "Grange FC".to_string(),
            founded_year: 1873,
            ground: "Intake Road".to_string(),
            origin: "played at Intake Road".to_string(),
            city: Some("Intake".to_string()),
            region: Some("S12".to_string()),
        },
        SheffieldClub {
            id: "pitsmoor-coal-company-fc".to_string(),
            name: "Pitsmoor Coal Company FC".to_string(),
            founded_year: 1873,
            ground: "Brightside".to_string(),
            origin: "From Brightside".to_string(),
            city: Some("Brightside".to_string()),
            region: Some("S4".to_string()),
        },
        SheffieldClub {
            id: "boston-street-fc".to_string(),
            name: "Boston Street FC".to_string(),
            founded_year: 1873,
            ground: "Heeley".to_string(),
            origin: "From Boston Street, played in Heeley".to_string(),
            city: Some("Heeley".to_string()),
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "birley-fc".to_string(),
            name: "Birley FC".to_string(),
            founded_year: 1873,
            ground: "Hollinsend".to_string(),
            origin: "played at Hollinsend, Birley".to_string(),
            city: None,
            region: Some("S12".to_string()),
        },
        SheffieldClub {
            id: "sherrington-fc".to_string(),
            name: "Sherrington FC".to_string(),
            founded_year: 1873,
            ground: "Norfolk Park".to_string(),
            origin: "From Sherrington Road, Sharrow, played Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        // 1874 - Continued expansion
        SheffieldClub {
            id: "105th-regiment".to_string(),
            name: "105th Regiment".to_string(),
            founded_year: 1874,
            ground: "Unknown".to_string(),
            origin: "Joined FA in 1874. Played in FA Cup 1875 to 1879.Nickname was 'Light Bobs'".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "carnforth-fc".to_string(),
            name: "Carnforth FC".to_string(),
            founded_year: 1874,
            ground: "Sharrow Vale Road".to_string(),
            origin: "played at Sharrow Vale Road".to_string(),
            city: Some("Sharrow".to_string()),
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "hollinsend-fc".to_string(),
            name: "Hollinsend FC".to_string(),
            founded_year: 1874,
            ground: "Unknown".to_string(),
            origin: "Other".to_string(),
            city: None,
            region: Some("S12".to_string()),
        },
        SheffieldClub {
            id: "providence-fc".to_string(),
            name: "Providence FC".to_string(),
            founded_year: 1874,
            ground: "Park Hill Lane".to_string(),
            origin: "played at Park Hill Lane".to_string(),
            city: Some("Park Hill".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "handsworth-fc".to_string(),
            name: "Handsworth FC".to_string(),
            founded_year: 1874,
            ground: "Unknown".to_string(),
            origin: "Ground unknown".to_string(),
            city: None,
            region: Some("S13".to_string()),
        },
        SheffieldClub {
            id: "woodseats-fc".to_string(),
            name: "Woodseats FC".to_string(),
            founded_year: 1874,
            ground: "Woodseats Hotel".to_string(),
            origin: "Met at the Woodseats Hotel, now Viraaj".to_string(),
            city: Some("Woodseats".to_string()),
            region: Some("S8".to_string()),
        },
        SheffieldClub {
            id: "oak-street-fc".to_string(),
            name: "Oak Street FC".to_string(),
            founded_year: 1874,
            ground: "Heeley".to_string(),
            origin: "From street of same name, Heeley".to_string(),
            city: Some("Heeley".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "atlas-fc".to_string(),
            name: "Atlas FC".to_string(),
            founded_year: 1874,
            ground: "East End".to_string(),
            origin: "formed from Atlas Works, East End".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "ecclesall-fc".to_string(),
            name: "Ecclesall FC".to_string(),
            founded_year: 1874,
            ground: "Hunters Bar".to_string(),
            origin: "played at Hunters Bar".to_string(),
            city: None,
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "nether-fc".to_string(),
            name: "Nether FC".to_string(),
            founded_year: 1874,
            ground: "Eastborne".to_string(),
            origin: "played at Eastborne".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "broomfield-fc".to_string(),
            name: "Broomfield FC".to_string(),
            founded_year: 1874,
            ground: "Broomfield".to_string(),
            origin: "From Broomfield area of Sheffield".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "st-mark-fc".to_string(),
            name: "St Mark's FC".to_string(),
            founded_year: 1874,
            ground: "Broomfield Road".to_string(),
            origin: "From St Mark's Broomfield Road".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "tabernacle-fc".to_string(),
            name: "Tabernacle FC".to_string(),
            founded_year: 1874,
            ground: "Albert Terrace Road".to_string(),
            origin: "From Tabernacle Church, Albert Terrace Road".to_string(),
            city: None,
            region: Some("S8".to_string()),
        },
        SheffieldClub {
            id: "st-michael-angels-fc".to_string(),
            name: "St Michaels Angels FC".to_string(),
            founded_year: 1874,
            ground: "Parkwood Springs".to_string(),
            origin: "From St Michael's Church, Parkwood Springs".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "kenwood-fc".to_string(),
            name: "Kenwood FC".to_string(),
            founded_year: 1874,
            ground: "Abbeydale Road".to_string(),
            origin: "played at a ground oﬀ Abbeydale Road".to_string(),
            city: None,
            region: Some("S7".to_string()),
        },
        SheffieldClub {
            id: "port-mahon-fc".to_string(),
            name: "Port Mahon FC".to_string(),
            founded_year: 1874,
            ground: "Port Mahon".to_string(),
            origin: "From Port Mahon, now Ponderosa".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "st-luke-fc".to_string(),
            name: "St Luke's FC".to_string(),
            founded_year: 1874,
            ground: "Park".to_string(),
            origin: "From St Luke's, Park (behind Midland Station),".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "heeley-victoria-fc".to_string(),
            name: "Heeley Victoria FC".to_string(),
            founded_year: 1874,
            ground: "Heeley".to_string(),
            origin: "From Victoria Hotel in Heeley".to_string(),
            city: Some("Heeley".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "shrewsbury-road-fc".to_string(),
            name: "Shrewsbury Road FC".to_string(),
            founded_year: 1874,
            ground: "Behind Midland Station".to_string(),
            origin: "Road of same name behind Midland station".to_string(),
            city: None,
            region: Some("S8".to_string()),
        },
        SheffieldClub {
            id: "park-united-fc".to_string(),
            name: "Park United FC".to_string(),
            founded_year: 1874,
            ground: "Park".to_string(),
            origin: "From Park area".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "white-star-fc".to_string(),
            name: "White Star FC".to_string(),
            founded_year: 1874,
            ground: "Unknown".to_string(),
            origin: "Location origins unknown".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "good-intent-fc".to_string(),
            name: "Good Intent FC".to_string(),
            founded_year: 1874,
            ground: "Truro Ground, Matilda Street".to_string(),
            origin: "Likely played at Truro Ground on Matilda Street".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "mount-tabor-fc".to_string(),
            name: "Mount Tabor FC".to_string(),
            founded_year: 1874,
            ground: "City Centre".to_string(),
            origin: "Church in city centre, now demolish".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "st-jude-fc".to_string(),
            name: "St Jude's FC".to_string(),
            founded_year: 1874,
            ground: "Cupola Street".to_string(),
            origin: "From St Jude's church on Cupola Street".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "wingfield-rowbotham-fc".to_string(),
            name: "Wingfield & Rowbotham FC".to_string(),
            founded_year: 1874,
            ground: "Tenter Street".to_string(),
            origin: "From their works on Tenter Street".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "young-broomhall-fc".to_string(),
            name: "Young Broomhall FC".to_string(),
            founded_year: 1874,
            ground: "Unknown".to_string(),
            origin: "Ground location unknown".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "regents-works-fc".to_string(),
            name: "Regents Works FC".to_string(),
            founded_year: 1874,
            ground: "Penistone Road".to_string(),
            origin: "Regents Works, now Wicks on Penistone Road".to_string(),
            city: Some("Penistone".to_string()),
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "lo-good-templars-fc".to_string(),
            name: "L. O. Good Templars FC".to_string(),
            founded_year: 1874,
            ground: "Unknown".to_string(),
            origin: "Origins unknown".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "brookes-crookes-fc".to_string(),
            name: "Brookes & Crookes FC".to_string(),
            founded_year: 1874,
            ground: "Brook Lane".to_string(),
            origin: "From Brook Steel Works, Brook Lane".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "polar-star-fc".to_string(),
            name: "Polar Star FC".to_string(),
            founded_year: 1874,
            ground: "Norfolk Park".to_string(),
            origin: "played at Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "norton-mount-view-fc".to_string(),
            name: "Norton Mount View FC".to_string(),
            founded_year: 1874,
            ground: "Norton Lees".to_string(),
            origin: "From Mount View Methodists Church, Norton Lees".to_string(),
            city: Some("Norton Lees".to_string()),
            region: Some("S8".to_string()),
        },
        SheffieldClub {
            id: "mill-sands-fc".to_string(),
            name: "Mill Sands FC".to_string(),
            founded_year: 1874,
            ground: "Mill Sands Works".to_string(),
            origin: "From Mill Sands Works, now Vulcan House".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "fenton-brothers-fc".to_string(),
            name: "Fenton Brothers FC".to_string(),
            founded_year: 1874,
            ground: "East Street, Park".to_string(),
            origin: "From their works, East Street, Park".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "sir-john-brown-fc".to_string(),
            name: "Sir John Brown's FC".to_string(),
            founded_year: 1874,
            ground: "Osgathorpe".to_string(),
            origin: "played at Osgathorpe, near Earl Marshall".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "st-silas-fc".to_string(),
            name: "St Silas FC".to_string(),
            founded_year: 1874,
            ground: "Broomhall".to_string(),
            origin: "From St Silas Church, Broomhall".to_string(),
            city: Some("Broomhall".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "ecclesall-church-fc".to_string(),
            name: "Ecclesall Church FC".to_string(),
            founded_year: 1874,
            ground: "Ecclesall".to_string(),
            origin: "From Ecclesall All Saints".to_string(),
            city: Some("Ecclesall".to_string()),
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "firth-fc".to_string(),
            name: "Firth's FC".to_string(),
            founded_year: 1874,
            ground: "East End".to_string(),
            origin: "From Thomas Firth & Son's, east end".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "owlerton-united-fc".to_string(),
            name: "Owlerton United FC".to_string(),
            founded_year: 1874,
            ground: "Wadsley Bridge".to_string(),
            origin: "played at Wadsley Bridge".to_string(),
            city: Some("Wadsley Bridge".to_string()),
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "atkin-brothers-fc".to_string(),
            name: "Atkin Brothers FC".to_string(),
            founded_year: 1874,
            ground: "Matilda Street".to_string(),
            origin: "From Truro Works, Matilda Street".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "unitarian-fc".to_string(),
            name: "Unitarian FC".to_string(),
            founded_year: 1874,
            ground: "Norfolk Street".to_string(),
            origin: "From Unitarian Church, Norfolk Street".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "deep-pits-fc".to_string(),
            name: "Deep Pits FC".to_string(),
            founded_year: 1874,
            ground: "City Road".to_string(),
            origin: "Near Manor Top, on City Road".to_string(),
            city: Some("Manor".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "sheaf-fc".to_string(),
            name: "Sheaf FC".to_string(),
            founded_year: 1874,
            ground: "Victoria Station".to_string(),
            origin: "From Sheaf Works next to Victoria station".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "montague-fc".to_string(),
            name: "Montague FC".to_string(),
            founded_year: 1874,
            ground: "Sharrow".to_string(),
            origin: "From Montague Street Sharrow".to_string(),
            city: Some("Sharrow".to_string()),
            region: Some("S7".to_string()),
        },
        // 1875 - Final major expansion before FA standardization
        SheffieldClub {
            id: "collegiate-fc".to_string(),
            name: "Collegiate FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "(exact date unknown)".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "stag-home-fc".to_string(),
            name: "Stag Home FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "Origins uncertain, possibly played at Kenwood".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "stanley-street-fc".to_string(),
            name: "Stanley Street FC".to_string(),
            founded_year: 1875,
            ground: "Norfolk Park".to_string(),
            origin: "From Stanley Street, Wicker, played mainly at Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "langsett-road-fc".to_string(),
            name: "Langsett Road FC".to_string(),
            founded_year: 1875,
            ground: "Queens Ground".to_string(),
            origin: "Likely played at Queens Ground".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "manor-fc".to_string(),
            name: "Manor FC".to_string(),
            founded_year: 1875,
            ground: "Manor Lane".to_string(),
            origin: "played at Manor Lane".to_string(),
            city: Some("Manor".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "wheatman-smith-fc".to_string(),
            name: "Wheatman & Smith's FC".to_string(),
            founded_year: 1875,
            ground: "Russell Works".to_string(),
            origin: "From Russell Works, near Kelham Island".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "netherthorpe-fc".to_string(),
            name: "Netherthorpe FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "Ground location uncertain".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "st-peter-fc".to_string(),
            name: "St Peter's FC".to_string(),
            founded_year: 1875,
            ground: "Myrtle Road".to_string(),
            origin: "From the now Cathedral, played at Myrtle Road".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "st-philip-fc".to_string(),
            name: "St Philip's FC".to_string(),
            founded_year: 1875,
            ground: "Netherthorpe".to_string(),
            origin: "From St Philip's church, Netherthorpe".to_string(),
            city: None,
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "dronfield-united-fc".to_string(),
            name: "Dronfield United FC".to_string(),
            founded_year: 1875,
            ground: "Dronfield".to_string(),
            origin: "From Dronfield".to_string(),
            city: None,
            region: Some("S18".to_string()),
        },
        SheffieldClub {
            id: "hope-club".to_string(),
            name: "Hope Club".to_string(),
            founded_year: 1875,
            ground: "Weston Field".to_string(),
            origin: "From Hope Works on Sussex Road, Played at Weston Field".to_string(),
            city: Some("Hope".to_string()),
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "brown-bailey-dixon-fc".to_string(),
            name: "Brown Bailey & Dixon FC".to_string(),
            founded_year: 1875,
            ground: "Attercliffe".to_string(),
            origin: "From their AUercliﬀe works, Leeds Road".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "ward-payne-fc".to_string(),
            name: "Ward & Payne's FC".to_string(),
            founded_year: 1875,
            ground: "Limbrick Works, Hillsborough".to_string(),
            origin: "From their Limbrick Works, Hillsborough".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "crookes-united-fc".to_string(),
            name: "Crookes United FC".to_string(),
            founded_year: 1875,
            ground: "Lydgate Lane".to_string(),
            origin: "Likely played at Lydgate Lane".to_string(),
            city: None,
            region: Some("S10".to_string()),
        },
        SheffieldClub {
            id: "harold-fc".to_string(),
            name: "Harold FC".to_string(),
            founded_year: 1875,
            ground: "Walkley".to_string(),
            origin: "Likely from Harold Street, Walkley".to_string(),
            city: Some("Walkley".to_string()),
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "huffton-son-fc".to_string(),
            name: "Huffton & Son FC".to_string(),
            founded_year: 1875,
            ground: "West Street".to_string(),
            origin: "From Huffton's Works, West Street".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "malinda-works-fc".to_string(),
            name: "Malinda Works FC".to_string(),
            founded_year: 1875,
            ground: "Malinda Street".to_string(),
            origin: "From Malinda Works, Malinda Street".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "parkwood-juniors-fc".to_string(),
            name: "Parkwood Juniors FC".to_string(),
            founded_year: 1875,
            ground: "Parkwood Springs".to_string(),
            origin: "From Parkwood Springs".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "aston-fc".to_string(),
            name: "Aston FC".to_string(),
            founded_year: 1875,
            ground: "Aston".to_string(),
            origin: "From Aston".to_string(),
            city: Some("Aston".to_string()),
            region: Some("S26".to_string()),
        },
        SheffieldClub {
            id: "washington-fc".to_string(),
            name: "Washington FC".to_string(),
            founded_year: 1875,
            ground: "Washington Street".to_string(),
            origin: "From Wostenholm's Washington Works, Washington Street, poss played at Cobden View".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "st-paul-fc".to_string(),
            name: "St Paul's FC".to_string(),
            founded_year: 1875,
            ground: "Peace Gardens".to_string(),
            origin: "From St Paul's church , now Peace Gardens".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "south-view-fc".to_string(),
            name: "South View FC".to_string(),
            founded_year: 1875,
            ground: "Machon Bank".to_string(),
            origin: "From South View Road in Sharrow, played at Machon Bank".to_string(),
            city: Some("Sharrow".to_string()),
            region: Some("S7".to_string()),
        },
        SheffieldClub {
            id: "ecclesall-united-fc".to_string(),
            name: "Ecclesall United FC".to_string(),
            founded_year: 1875,
            ground: "Ecclesall".to_string(),
            origin: "played at Ecclesall".to_string(),
            city: Some("Ecclesall".to_string()),
            region: Some("S11".to_string()),
        },
        SheffieldClub {
            id: "msl-loco-fc".to_string(),
            name: "MS&L Loco FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "Ground location unknown".to_string(),
            city: None,
            region: Some("S4".to_string()),
        },
        SheffieldClub {
            id: "oxford-wanderers-fc".to_string(),
            name: "Oxford Wanderers FC".to_string(),
            founded_year: 1875,
            ground: "Norfolk Park".to_string(),
            origin: "Poss from Oxford Street, played Norfolk Park".to_string(),
            city: Some("Norfolk Park".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "dronfield-free-church-fc".to_string(),
            name: "Dronfield Free Church FC".to_string(),
            founded_year: 1875,
            ground: "Dronfield".to_string(),
            origin: "From Dronfield United Methodist Free Church, now Peel Centre, High Street, Dronfield".to_string(),
            city: None,
            region: Some("S18".to_string()),
        },
        SheffieldClub {
            id: "atlantic-juniors-fc".to_string(),
            name: "Atlantic (Juniors) FC".to_string(),
            founded_year: 1875,
            ground: "Cobden View".to_string(),
            origin: "played at Cobden View".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "wincobank-fc".to_string(),
            name: "Wincobank FC".to_string(),
            founded_year: 1875,
            ground: "Wincobank".to_string(),
            origin: "From Wincobank area".to_string(),
            city: Some("Wincobank".to_string()),
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "alexandra-fc".to_string(),
            name: "Alexandra FC".to_string(),
            founded_year: 1875,
            ground: "Alexandra Road, Heeley".to_string(),
            origin: "From Alexandra Road, Heeley".to_string(),
            city: Some("Heeley".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "carbrook-united-fc".to_string(),
            name: "Carbrook United FC".to_string(),
            founded_year: 1875,
            ground: "Carbrook".to_string(),
            origin: "played behind St Batholowmew's Church Carbrook".to_string(),
            city: None,
            region: Some("S9".to_string()),
        },
        SheffieldClub {
            id: "r-sorby-son-fc".to_string(),
            name: "R Sorby & Son FC".to_string(),
            founded_year: 1875,
            ground: "Trafalgar Street".to_string(),
            origin: "From Kangaroo Works, Trafalgar Street".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "upperthorpe-fc".to_string(),
            name: "Upperthorpe FC".to_string(),
            founded_year: 1875,
            ground: "Cobden View".to_string(),
            origin: "played at Cobden View".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "howard-street-fc".to_string(),
            name: "Howard Street FC".to_string(),
            founded_year: 1875,
            ground: "Heeley".to_string(),
            origin: "Likely played in Heeley, from Howard Street".to_string(),
            city: Some("Heeley".to_string()),
            region: Some("S2".to_string()),
        },
        SheffieldClub {
            id: "otley-son-fc".to_string(),
            name: "Otley & Son's FC".to_string(),
            founded_year: 1875,
            ground: "Shalesmoor".to_string(),
            origin: "From Meadow Works Shalesmoor".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "hillsborough-fc".to_string(),
            name: "Hillsborough / Hillsborough School FC".to_string(),
            founded_year: 1875,
            ground: "Hillsborough".to_string(),
            origin: "played at Hillsborough".to_string(),
            city: Some("Hillsborough".to_string()),
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "bellefield-fc".to_string(),
            name: "Bellefield FC".to_string(),
            founded_year: 1875,
            ground: "Bellefield Lane, Netherthorpe".to_string(),
            origin: "From Bellefield Works, Bellefield Lane, Netherthorpe".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "red-rose-fc".to_string(),
            name: "Red Rose FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "Could be from Pitsmoor or Bramall Lane or was possibly 2 clubs".to_string(),
            city: Some("Pitsmoor".to_string()),
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "weston-rovers-fc".to_string(),
            name: "Weston Rovers FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "Uncertain origins".to_string(),
            city: None,
            region: Some("S1".to_string()),
        },
        SheffieldClub {
            id: "j-round-son-fc".to_string(),
            name: "J Round & Son FC".to_string(),
            founded_year: 1875,
            ground: "Tudor Street".to_string(),
            origin: "From Tudor Works, Tudor Street, now Tudor Sq".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "dronfield-baptists-fc".to_string(),
            name: "Dronfield Baptist FC".to_string(),
            founded_year: 1875,
            ground: "Dronfield".to_string(),
            origin: "Church".to_string(),
            city: None,
            region: Some("S18".to_string()),
        },
        SheffieldClub {
            id: "pye-bank-free-church-fc".to_string(),
            name: "Pye Bank Free Church FC".to_string(),
            founded_year: 1875,
            ground: "Pye Bank".to_string(),
            origin: "Pye Bank, Sheﬃeld".to_string(),
            city: None,
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "dronfield-independent-fc".to_string(),
            name: "Dronfield Independent FC".to_string(),
            founded_year: 1875,
            ground: "Dronfield".to_string(),
            origin: "From Independent Chapel Lea Road, Dronfield".to_string(),
            city: None,
            region: Some("S18".to_string()),
        },
        SheffieldClub {
            id: "ebenezer-reform-fc".to_string(),
            name: "Ebenezer Reform FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "Ebenezer Chaple, Neepsend".to_string(),
            city: None,
            region: Some("S6".to_string()),
        },
        SheffieldClub {
            id: "clough-house-fc".to_string(),
            name: "Clough House FC".to_string(),
            founded_year: 1875,
            ground: "Clough area near Bramall Lane".to_string(),
            origin: "Likley from The Clough area near Bramall Lane".to_string(),
            city: None,
            region: None,
        },
        SheffieldClub {
            id: "trinity-fc".to_string(),
            name: "Trinity FC".to_string(),
            founded_year: 1875,
            ground: "Trinity Works".to_string(),
            origin: "From George Butler & Co, Trinity Works".to_string(),
            city: None,
            region: None,
        },
        SheffieldClub {
            id: "wostenholm-fc".to_string(),
            name: "Wostenholm FC".to_string(),
            founded_year: 1875,
            ground: "Washington Works".to_string(),
            origin: "club from Washington Works".to_string(),
            city: None,
            region: None,
        },
        SheffieldClub {
            id: "bee-hive-works-fc".to_string(),
            name: "Bee Hive Works FC".to_string(),
            founded_year: 1875,
            ground: "Bee Hive Works, Neepsend".to_string(),
            origin: "From Bee Hive Works Neepsend (not Milton St)".to_string(),
            city: Some("Neepsend".to_string()),
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "chester-brothers-fc".to_string(),
            name: "Chester Brothers FC".to_string(),
            founded_year: 1875,
            ground: "West End Cutlery Works, West Street".to_string(),
            origin: "From West End Cuterly Works West Street".to_string(),
            city: None,
            region: None,
        },
        SheffieldClub {
            id: "heeley-united-fc".to_string(),
            name: "Heeley United FC".to_string(),
            founded_year: 1875,
            ground: "Unknown".to_string(),
            origin: "Unknown origins".to_string(),
            city: None,
            region: None,
        },
        SheffieldClub {
            id: "cornish-place-fc".to_string(),
            name: "Cornish Place FC".to_string(),
            founded_year: 1875,
            ground: "Cornish Works, Neepsend".to_string(),
            origin: "From Cornish Works, Neepsend".to_string(),
            city: Some("Neepsend".to_string()),
            region: Some("S3".to_string()),
        },
        SheffieldClub {
            id: "minerva-fc".to_string(),
            name: "Minerva FC".to_string(),
            founded_year: 1875,
            ground: "John Street".to_string(),
            origin: "From their works on John Street".to_string(),
            city: None,
            region: None,
        },
        SheffieldClub {
            id: "woodhouse-fc".to_string(),
            name: "Woodhouse FC".to_string(),
            founded_year: 1875,
            ground: "Woodhouse".to_string(),
            origin: "From Woodhouse".to_string(),
            city: Some("Woodhouse".to_string()),
            region: Some("S13".to_string()),
        },
        SheffieldClub {
            id: "kenyons-works-fc".to_string(),
            name: "Kenyon's Works FC".to_string(),
            founded_year: 1875,
            ground: "Hollins Crog".to_string(),
            origin: "From Kenyon Works, Hollins Crog".to_string(),
            city: None,
            region: None,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_clubs_count() {
        assert_eq!(all_clubs_data().len(), 187);
    }

    #[test]
    fn test_sheffield_fc_is_oldest() {
        let clubs = all_clubs_data();
        let oldest = clubs.iter().min_by_key(|c| c.founded_year).unwrap();
        assert_eq!(oldest.name, "Sheffield FC");
        assert_eq!(oldest.founded_year, 1857);
    }

    #[test]
    fn test_filter_by_year() {
        let clubs_by_1862 = get_sheffield_clubs(Some(1862));
        let clubs_by_1873 = get_sheffield_clubs(Some(1873));

        assert!(clubs_by_1862.len() < clubs_by_1873.len());
    }

    #[test]
    fn test_wednesday_fc_founded_1867() {
        let clubs = get_sheffield_clubs(Some(1867));
        let wednesday = clubs.iter()
            .find(|c| c.name == "Wednesday FC")
            .unwrap();
        assert_eq!(wednesday.founded_year, 1867);
    }

    #[test]
    fn test_clubs_by_origin_type() {
        let all = all_clubs_data();
        let church_clubs = all.iter().filter(|c| c.origin == "Church").count();
        let works_clubs = all.iter().filter(|c| c.origin == "Works").count();

        assert!(church_clubs > 0);
        assert!(works_clubs > 0);
    }
}
